// Date: 27/06/2012 6:20:29 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package pixelmon.Pokemon;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelVibrava extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer LeftEye;
    ModelRenderer RightEye;
    ModelRenderer Top1;
    ModelRenderer Top2;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
    ModelRenderer Tail4;
    ModelRenderer Tail5;
    ModelRenderer Head1;
    ModelRenderer Head2;
    ModelRenderer Head3;
    ModelRenderer Leg1;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Leg5;
    ModelRenderer Leg6;
    ModelRenderer Leg7;
    ModelRenderer Leg8;
    ModelRenderer Leg9;
    ModelRenderer Leg10;
    ModelRenderer Leg11;
    ModelRenderer Leg12;
    ModelRenderer Teeth1;
    ModelRenderer Teeth2;
    ModelRenderer Piece1;
    ModelRenderer Piece2;
    ModelRenderer Piece3;
    ModelRenderer Piece4;
    ModelRenderer Leg2;
    ModelRenderer Wing1;
    ModelRenderer Wing2;
    ModelRenderer Wing3;
    ModelRenderer Wing4;
    
  
  public ModelVibrava()
  {
    textureWidth = 64;
    textureHeight = 32;
    setTextureOffset("Piece1.Folder1", 0, 0);
    setTextureOffset("Piece2.Folder2", 0, 0);
    setTextureOffset("Piece3.Folder3", 0, 0);
    setTextureOffset("Piece4.Folder4", 0, 0);
    
      Body = new ModelRenderer(this, 42, 0);
      Body.addBox(0F, 0F, 0F, 3, 3, 8);
      Body.setRotationPoint(0F, 18.5F, -4F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      LeftEye = new ModelRenderer(this, 58, 0);
      LeftEye.addBox(0F, 0F, 0F, 1, 2, 2);
      LeftEye.setRotationPoint(2.7F, 18.5F, -7.5F);
      LeftEye.setTextureSize(64, 32);
      LeftEye.mirror = true;
      setRotation(LeftEye, 0F, 0F, 0F);
      RightEye = new ModelRenderer(this, 42, 0);
      RightEye.addBox(0F, 0F, 0F, 1, 2, 2);
      RightEye.setRotationPoint(-0.7F, 18.5F, -7.5F);
      RightEye.setTextureSize(64, 32);
      RightEye.mirror = true;
      setRotation(RightEye, 0F, 0F, 0F);
      Top1 = new ModelRenderer(this, 43, 5);
      Top1.addBox(0F, 0F, 0F, 1, 1, 1);
      Top1.setRotationPoint(1.8F, 18.3F, -0.8F);
      Top1.setTextureSize(64, 32);
      Top1.mirror = true;
      setRotation(Top1, 0F, 0F, 0F);
      Top2 = new ModelRenderer(this, 43, 5);
      Top2.addBox(0F, 0F, 0F, 1, 1, 1);
      Top2.setRotationPoint(0.2F, 18.3F, -0.8F);
      Top2.setTextureSize(64, 32);
      Top2.mirror = true;
      setRotation(Top2, 0F, 0F, 0F);
      Tail1 = new ModelRenderer(this, 50, 25);
      Tail1.addBox(0F, 0F, 0F, 2, 2, 5);
      Tail1.setRotationPoint(0.5F, 19F, 3F);
      Tail1.setTextureSize(64, 32);
      Tail1.mirror = true;
      setRotation(Tail1, 0.2792527F, 0F, 0F);
      Tail2 = new ModelRenderer(this, 36, 25);
      Tail2.addBox(0F, 0F, 0F, 1, 1, 6);
      Tail2.setRotationPoint(1F, 18.5F, 6.5F);
      Tail2.setTextureSize(64, 32);
      Tail2.mirror = true;
      setRotation(Tail2, 0.418879F, 0F, 0F);
      Tail3 = new ModelRenderer(this, 46, 25);
      Tail3.addBox(0F, 0F, 0F, 1, 1, 2);
      Tail3.setRotationPoint(1F, 16.3F, 11.6F);
      Tail3.setTextureSize(64, 32);
      Tail3.mirror = true;
      setRotation(Tail3, 0.8028515F, 0F, 0F);
      Tail4 = new ModelRenderer(this, 24, 27);
      Tail4.addBox(0F, 0F, 0F, 3, 0, 5);
      Tail4.setRotationPoint(1.8F, 15.2F, 13F);
      Tail4.setTextureSize(64, 32);
      Tail4.mirror = true;
      setRotation(Tail4, 0.1745329F, 0.3665191F, 0.3490659F);
      Tail5 = new ModelRenderer(this, 24, 27);
      Tail5.addBox(-3F, 0F, 0F, 3, 0, 5);
      Tail5.setRotationPoint(1.2F, 15.2F, 13F);
      Tail5.setTextureSize(64, 32);
      Tail5.mirror = true;
      setRotation(Tail5, 0.1745329F, -0.3665191F, -0.3490659F);
      Head1 = new ModelRenderer(this, 20, 13);
      Head1.addBox(0F, 0F, 0F, 4, 4, 4);
      Head1.setRotationPoint(-0.5F, 18F, -8F);
      Head1.setTextureSize(64, 32);
      Head1.mirror = true;
      setRotation(Head1, 0F, 0F, 0F);
      Head2 = new ModelRenderer(this, 0, 14);
      Head2.addBox(0F, 0F, 0F, 1, 1, 4);
      Head2.setRotationPoint(-0.9F, 16.5F, -10F);
      Head2.setTextureSize(64, 32);
      Head2.mirror = true;
      setRotation(Head2, -0.4014257F, 0.1919862F, 0F);
      Head3 = new ModelRenderer(this, 0, 14);
      Head3.addBox(-1F, 0F, 0F, 1, 1, 4);
      Head3.setRotationPoint(3.9F, 16.5F, -10F);
      Head3.setTextureSize(64, 32);
      Head3.mirror = true;
      setRotation(Head3, -0.4014257F, -0.1919862F, 0F);
      Leg1 = new ModelRenderer(this, 0, 0);
      Leg1.addBox(-1F, 0F, 0F, 1, 2, 1);
      Leg1.setRotationPoint(4.2F, 21.5F, -3F);
      Leg1.setTextureSize(64, 32);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, -0.4537856F);
      Leg3 = new ModelRenderer(this, 0, 0);
      Leg3.addBox(-1F, 0F, 0F, 3, 1, 1);
      Leg3.setRotationPoint(2.3F, 21F, -3F);
      Leg3.setTextureSize(64, 32);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0.2617994F);
      Leg4 = new ModelRenderer(this, 0, 0);
      Leg4.addBox(-1F, 0F, 0F, 1, 2, 1);
      Leg4.setRotationPoint(4.2F, 21.5F, -1F);
      Leg4.setTextureSize(64, 32);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, -0.4537856F);
      Leg5 = new ModelRenderer(this, 0, 0);
      Leg5.addBox(0F, 0F, 0F, 1, 2, 1);
      Leg5.setRotationPoint(5.4F, 22.8F, -1F);
      Leg5.setTextureSize(64, 32);
      Leg5.mirror = true;
      setRotation(Leg5, 0F, 0F, 1.413717F);
      Leg6 = new ModelRenderer(this, 0, 0);
      Leg6.addBox(-1F, 0F, 0F, 3, 1, 1);
      Leg6.setRotationPoint(2.3F, 21F, -1F);
      Leg6.setTextureSize(64, 32);
      Leg6.mirror = true;
      setRotation(Leg6, 0F, 0F, 0.2617994F);
      Leg7 = new ModelRenderer(this, 0, 0);
      Leg7.addBox(0F, 0F, 0F, 1, 2, 1);
      Leg7.setRotationPoint(-1.1F, 21.5F, -3F);
      Leg7.setTextureSize(64, 32);
      Leg7.mirror = true;
      setRotation(Leg7, 0F, 0F, 0.4537856F);
      Leg8 = new ModelRenderer(this, 0, 0);
      Leg8.addBox(0F, -2F, 0F, 1, 2, 1);
      Leg8.setRotationPoint(-0.5F, 24.1F, -3F);
      Leg8.setTextureSize(64, 32);
      Leg8.mirror = true;
      setRotation(Leg8, 0F, 0F, -1.413717F);
      Leg9 = new ModelRenderer(this, 0, 0);
      Leg9.addBox(-2F, 0F, 0F, 3, 1, 1);
      Leg9.setRotationPoint(0.8F, 21F, -3F);
      Leg9.setTextureSize(64, 32);
      Leg9.mirror = true;
      setRotation(Leg9, 0F, 0F, -0.2617994F);
      Leg10 = new ModelRenderer(this, 0, 0);
      Leg10.addBox(0F, 0F, 0F, 1, 2, 1);
      Leg10.setRotationPoint(-1.1F, 21.5F, -1F);
      Leg10.setTextureSize(64, 32);
      Leg10.mirror = true;
      setRotation(Leg10, 0F, 0F, 0.4537856F);
      Leg11 = new ModelRenderer(this, 0, 0);
      Leg11.addBox(0F, -2F, 0F, 1, 2, 1);
      Leg11.setRotationPoint(-0.5F, 24.1F, -1F);
      Leg11.setTextureSize(64, 32);
      Leg11.mirror = true;
      setRotation(Leg11, 0F, 0F, -1.413717F);
      Leg12 = new ModelRenderer(this, 0, 0);
      Leg12.addBox(-2F, 0F, 0F, 3, 1, 1);
      Leg12.setRotationPoint(0.8F, 21F, -1F);
      Leg12.setTextureSize(64, 32);
      Leg12.mirror = true;
      setRotation(Leg12, 0F, 0F, -0.2617994F);
      Teeth1 = new ModelRenderer(this, 15, 0);
      Teeth1.addBox(0F, 0F, 0F, 1, 1, 0);
      Teeth1.setRotationPoint(0F, 21F, -8F);
      Teeth1.setTextureSize(64, 32);
      Teeth1.mirror = true;
      setRotation(Teeth1, -0.1047198F, 0F, 0F);
      Teeth2 = new ModelRenderer(this, 15, 0);
      Teeth2.addBox(0F, 0F, 0F, 1, 1, 0);
      Teeth2.setRotationPoint(2F, 21F, -8F);
      Teeth2.setTextureSize(64, 32);
      Teeth2.mirror = true;
      setRotation(Teeth2, -0.1047198F, 0F, 0F);
    Piece1 = new ModelRenderer(this, "Piece1");
    Piece1.setRotationPoint(0F, 0F, 0F);
    setRotation(Piece1, 0F, 0F, 0F);
    Piece1.mirror = true;
   
      Wing1 = new ModelRenderer(this, 0, 25);
      Wing1.addBox(0F, 0F, 0F, 5, 0, 7);
      Wing1.setRotationPoint(2F, 18.5F, 0F);
      Wing1.setTextureSize(64, 32);
      Wing1.mirror = true;
      setRotation(Wing1, 0.6981317F, 0.4537856F, 0F);
    Piece2 = new ModelRenderer(this, "Piece2");
    Piece2.setRotationPoint(0F, 0F, 0F);
    setRotation(Piece2, 0F, 0F, 0F);
    Piece2.mirror = true;
      Wing2 = new ModelRenderer(this, 0, 25);
      Wing2.addBox(0F, 0F, 0F, 5, 0, 7);
      Wing2.setRotationPoint(2F, 18.5F, 0F);
      Wing2.setTextureSize(64, 32);
      Wing2.mirror = true;
      setRotation(Wing2, 0.5061455F, 0.4886922F, 0.1570796F);
    Piece3 = new ModelRenderer(this, "Piece3");
    Piece3.setRotationPoint(0F, 0F, 0F);
    setRotation(Piece3, 0F, 0F, 0F);
    Piece3.mirror = true;
      Wing3 = new ModelRenderer(this, 0, 25);
      Wing3.addBox(-5F, 0F, 0F, 5, 0, 7);
      Wing3.setRotationPoint(1F, 18.5F, 0F);
      Wing3.setTextureSize(64, 32);
      Wing3.mirror = true;
      setRotation(Wing3, 0.6981317F, -0.4537856F, 0F);
    Piece4 = new ModelRenderer(this, "Piece4");
    Piece4.setRotationPoint(0F, 0F, 0F);
    setRotation(Piece4, 0F, 0F, 0F);
    Piece4.mirror = true;
      Wing4 = new ModelRenderer(this, 0, 25);
      Wing4.addBox(-5F, 0F, 0F, 5, 0, 7);
      Wing4.setRotationPoint(1F, 18.5F, 0F);
      Wing4.setTextureSize(64, 32);
      Wing4.mirror = true;
      setRotation(Wing4, 0.5061455F, -0.4886922F, -0.1570796F);
      Leg2 = new ModelRenderer(this, 0, 0);
      Leg2.addBox(0F, 0F, 0F, 1, 2, 1);
      Leg2.setRotationPoint(5.4F, 22.8F, -3F);
      Leg2.setTextureSize(64, 32);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 1.413717F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
    LeftEye.render(f5);
    RightEye.render(f5);
    Top1.render(f5);
    Top2.render(f5);
    Tail1.render(f5);
    Tail2.render(f5);
    Tail3.render(f5);
    Tail4.render(f5);
    Tail5.render(f5);
    Head1.render(f5);
    Head2.render(f5);
    Head3.render(f5);
    Leg1.render(f5);
    Leg3.render(f5);
    Leg4.render(f5);
    Leg5.render(f5);
    Leg6.render(f5);
    Leg7.render(f5);
    Leg8.render(f5);
    Leg9.render(f5);
    Leg10.render(f5);
    Leg11.render(f5);
    Leg12.render(f5);
    Teeth1.render(f5);
    Teeth2.render(f5);
    Piece1.render(f5);
    Piece2.render(f5);
    Piece3.render(f5);
    Piece4.render(f5);
    Leg2.render(f5);
    Wing1.render(f5);
    Wing2.render(f5);
    Wing3.render(f5);
    Wing4.render(f5);
    
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
