// Date: 5/9/2012 5:07:26 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package pixelmon.Pokemon;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelGeodude extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Body1;
    ModelRenderer body2;
    ModelRenderer body3;
    ModelRenderer rightupperarm;
    ModelRenderer rightlowerarm;
    ModelRenderer leftlowerarm;
    ModelRenderer leftupperarm;
    ModelRenderer lefthand;
    ModelRenderer leftthumb;
    ModelRenderer leftfingers;
    ModelRenderer righthand;
    ModelRenderer rightthumb;
    ModelRenderer rightfingers;
  
  public ModelGeodude()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(-3F, -3F, -3F, 6, 6, 6);
      Body.setRotationPoint(0F, 20F, 1F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Body1 = new ModelRenderer(this, 0, 12);
      Body1.addBox(-2.5F, -3.5F, -2.5F, 5, 7, 5);
      Body1.setRotationPoint(0F, 20F, 1F);
      Body1.setTextureSize(64, 32);
      Body1.mirror = true;
      setRotation(Body1, 0F, 0F, 0F);
      body2 = new ModelRenderer(this, 24, 0);
      body2.addBox(-2.5F, -2.5F, -3.5F, 5, 5, 7);
      body2.setRotationPoint(0F, 20F, 1F);
      body2.setTextureSize(64, 32);
      body2.mirror = true;
      setRotation(body2, 0F, 0F, 0F);
      body3 = new ModelRenderer(this, 20, 12);
      body3.addBox(-3.5F, -2.5F, -2.5F, 7, 5, 5);
      body3.setRotationPoint(0F, 20F, 1F);
      body3.setTextureSize(64, 32);
      body3.mirror = true;
      setRotation(body3, 0F, 0F, 0F);
      rightupperarm = new ModelRenderer(this, 12, 26);
      rightupperarm.addBox(-7.8F, -0.5F, -0.5F, 5, 1, 1);
      rightupperarm.setRotationPoint(0F, 20F, 1F);
      rightupperarm.setTextureSize(64, 32);
      rightupperarm.mirror = true;
      setRotation(rightupperarm, 0F, 0F, 0F);
      rightlowerarm = new ModelRenderer(this, 0, 24);
      rightlowerarm.addBox(-1F, -1F, -4F, 2, 2, 4);
      rightlowerarm.setRotationPoint(-7F, 20F, 1F);
      rightlowerarm.setTextureSize(64, 32);
      rightlowerarm.mirror = true;
      setRotation(rightlowerarm, 0F, 0F, 0F);
      leftlowerarm = new ModelRenderer(this, 0, 24);
      leftlowerarm.addBox(-1F, -1F, -4F, 2, 2, 4);
      leftlowerarm.setRotationPoint(7F, 20F, 1F);
      leftlowerarm.setTextureSize(64, 32);
      leftlowerarm.mirror = true;
      setRotation(leftlowerarm, 0F, 0F, 0F);
      leftupperarm = new ModelRenderer(this, 12, 26);
      leftupperarm.addBox(2.8F, -0.5F, -0.5F, 5, 1, 1);
      leftupperarm.setRotationPoint(0F, 20F, 1F);
      leftupperarm.setTextureSize(64, 32);
      leftupperarm.mirror = true;
      setRotation(leftupperarm, 0F, 0F, 0F);
      lefthand = new ModelRenderer(this, 20, 22);
      lefthand.addBox(-2F, -1.5F, -2F, 4, 2, 2);
      lefthand.setRotationPoint(7F, 20F, -3F);
      lefthand.setTextureSize(64, 32);
      lefthand.mirror = true;
      setRotation(lefthand, 0F, 0F, 0F);
      leftthumb = new ModelRenderer(this, 12, 24);
      leftthumb.addBox(-2F, 0.5F, -1F, 3, 1, 1);
      leftthumb.setRotationPoint(7F, 20F, -3F);
      leftthumb.setTextureSize(64, 32);
      leftthumb.mirror = true;
      setRotation(leftthumb, 0F, 0F, 0F);
      leftfingers = new ModelRenderer(this, 0, 30);
      leftfingers.addBox(-2F, 0.5F, -2F, 4, 1, 1);
      leftfingers.setRotationPoint(7F, 20F, -3F);
      leftfingers.setTextureSize(64, 32);
      leftfingers.mirror = true;
      setRotation(leftfingers, 0F, 0F, 0F);
      righthand = new ModelRenderer(this, 20, 22);
      righthand.addBox(-2F, -1.5F, -2F, 4, 2, 2);
      righthand.setRotationPoint(-7F, 20F, -3F);
      righthand.setTextureSize(64, 32);
      righthand.mirror = true;
      setRotation(righthand, 0F, 0F, 0F);
      rightthumb = new ModelRenderer(this, 12, 24);
      rightthumb.addBox(-1F, 0.5F, -1F, 3, 1, 1);
      rightthumb.setRotationPoint(-7F, 20F, -3F);
      rightthumb.setTextureSize(64, 32);
      rightthumb.mirror = true;
      setRotation(rightthumb, 0F, 0F, 0F);
      rightfingers = new ModelRenderer(this, 0, 30);
      rightfingers.addBox(-2F, 0.5F, -2F, 4, 1, 1);
      rightfingers.setRotationPoint(-7F, 20F, -3F);
      rightfingers.setTextureSize(64, 32);
      rightfingers.mirror = true;
      setRotation(rightfingers, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
    Body1.render(f5);
    body2.render(f5);
    body3.render(f5);
    rightupperarm.render(f5);
    rightlowerarm.render(f5);
    leftlowerarm.render(f5);
    leftupperarm.render(f5);
    lefthand.render(f5);
    leftthumb.render(f5);
    leftfingers.render(f5);
    righthand.render(f5);
    rightthumb.render(f5);
    rightfingers.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
