// Date: 09/05/2012 21:25:43
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package pixelmon.Pokemon;

import net.minecraft.src.Entity;
import net.minecraft.src.MathHelper;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;


public class ModelPsyduck extends ModelBase
{
  //fields
    ModelRenderer right_foot;
    ModelRenderer left_foot;
    ModelRenderer lower_body;
    ModelRenderer mid_body;
    ModelRenderer upper_body;
    ModelRenderer head;
    ModelRenderer left_wing;
    ModelRenderer right_wing;
    ModelRenderer bill;
    ModelRenderer tail;
    ModelRenderer hair_middle;
    ModelRenderer hair_left;
    ModelRenderer hair_right;
  
  public ModelPsyduck()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      right_foot = new ModelRenderer(this, 24, 18);
      right_foot.addBox(-1F, 0F, -4F, 2, 1, 5);
      right_foot.setRotationPoint(3F, 23F, 0F);
      right_foot.setTextureSize(64, 32);
      right_foot.mirror = true;
      setRotation(right_foot, 0F, -0.3490659F, 0F);
      left_foot = new ModelRenderer(this, 24, 12);
      left_foot.addBox(-1F, 0F, -4F, 2, 1, 5);
      left_foot.setRotationPoint(-3F, 23F, 0F);
      left_foot.setTextureSize(64, 32);
      left_foot.mirror = true;
      setRotation(left_foot, 0F, 0.3490659F, 0F);
      lower_body = new ModelRenderer(this, 0, 12);
      lower_body.addBox(-4F, 7F, -2F, 7, 1, 5);
      lower_body.setRotationPoint(0.5F, 15F, 0.5F);
      lower_body.setTextureSize(64, 32);
      lower_body.mirror = true;
      setRotation(lower_body, 0F, 0F, 0F);
      mid_body = new ModelRenderer(this, 0, 0);
      mid_body.addBox(-4F, -6F, -3F, 8, 6, 6);
      mid_body.setRotationPoint(0F, 22F, 1F);
      mid_body.setTextureSize(64, 32);
      mid_body.mirror = true;
      setRotation(mid_body, 0F, 0F, 0F);
      upper_body = new ModelRenderer(this, 0, 18);
      upper_body.addBox(-4F, 0F, -2F, 7, 1, 5);
      upper_body.setRotationPoint(0.5F, 15F, 0.5F);
      upper_body.setTextureSize(64, 32);
      upper_body.mirror = true;
      setRotation(upper_body, 0F, 0F, 0F);
      head = new ModelRenderer(this, 28, 0);
      head.addBox(-2.5F, -4F, -2F, 5, 4, 4);
      head.setRotationPoint(0F, 15F, 1F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      left_wing = new ModelRenderer(this, 0, 24);
      left_wing.addBox(-5F, 0F, -2F, 5, 1, 3);
      left_wing.setRotationPoint(-4F, 17F, 1.5F);
      left_wing.setTextureSize(64, 32);
      left_wing.mirror = true;
      setRotation(left_wing, 0F, 0F, -0.8552113F);
      right_wing = new ModelRenderer(this, 0, 28);
      right_wing.addBox(0F, 0F, -2F, 5, 1, 3);
      right_wing.setRotationPoint(4F, 17F, 1.5F);
      right_wing.setTextureSize(64, 32);
      right_wing.mirror = true;
      setRotation(right_wing, 0F, 0F, 0.8552113F);
      bill = new ModelRenderer(this, 16, 24);
      bill.addBox(-2F, -2F, -5F, 4, 1, 4);
      bill.setRotationPoint(0F, 15F, 1F);
      bill.setTextureSize(64, 32);
      bill.mirror = true;
      setRotation(bill, 0.3316126F, 0F, 0F);
      tail = new ModelRenderer(this, 28, 24);
      tail.addBox(-1F, -1F, 0F, 2, 1, 4);
      tail.setRotationPoint(0F, 21F, 4F);
      tail.setTextureSize(64, 32);
      tail.mirror = true;
      setRotation(tail, 0.2792527F, 0F, 0F);
      hair_middle = new ModelRenderer(this, 30, 9);
      hair_middle.addBox(-0.5F, -6F, 2F, 1, 2, 0);
      hair_middle.setRotationPoint(0F, 15F, 1F);
      hair_middle.setTextureSize(64, 32);
      hair_middle.mirror = true;
      setRotation(hair_middle, 0F, 0F, 0F);
      hair_left = new ModelRenderer(this, 28, 9);
      hair_left.addBox(2F, -5F, 2F, 1, 2, 0);
      hair_left.setRotationPoint(0F, 15F, 1F);
      hair_left.setTextureSize(64, 32);
      hair_left.mirror = true;
      setRotation(hair_left, 0F, 0F, -0.7853982F);
      hair_right = new ModelRenderer(this, 32, 9);
      hair_right.addBox(-3F, -5F, 2F, 1, 2, 0);
      hair_right.setRotationPoint(0F, 15F, 1F);
      hair_right.setTextureSize(64, 32);
      hair_right.mirror = true;
      setRotation(hair_right, 0F, 0F, 0.7853982F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    right_foot.render(f5);
    left_foot.render(f5);
    lower_body.render(f5);
    mid_body.render(f5);
    upper_body.render(f5);
    head.render(f5);
    left_wing.render(f5);
    right_wing.render(f5);
    bill.render(f5);
    tail.render(f5);
    hair_middle.render(f5);
    hair_left.render(f5);
    hair_right.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
    
    left_foot.rotateAngleX =  MathHelper.cos(f * 1.5F) * .5F * f1;
    right_foot.rotateAngleX =  MathHelper.cos(f * 1.5F + 3.14159F) * .5F * f1;
    tail.rotateAngleY = MathHelper.cos(f * 1F) * .75F * f1;
    left_wing.rotateAngleZ = MathHelper.cos(f * 1F + 3.14159F) * .4F * f1 - 1;
    right_wing.rotateAngleZ = MathHelper.cos(f * 1F) * .4F * f1 + 1;
  }

}
