// Date: 5/6/2012 12:18:00 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package pixelmon.Pokemon;

import net.minecraft.src.*;

public class ModelAbra extends ModelBase
{
  //fields
    ModelRenderer BaseHead;
    ModelRenderer head;
    ModelRenderer uppermuzzle;
    ModelRenderer lowermuzzle;
    ModelRenderer rightear;
    ModelRenderer leftear;
    ModelRenderer righteye;
    ModelRenderer lefteye;
    ModelRenderer neck;
    ModelRenderer finger1;
    ModelRenderer finger2;
    ModelRenderer finger3;
    ModelRenderer upperbody;
    ModelRenderer lowerbody;
    ModelRenderer rightshoulder;
    ModelRenderer rightuppperarm;
    ModelRenderer rightlowerarm;
    ModelRenderer leftshoulder;
    ModelRenderer leftupperarm;
    ModelRenderer leftlowerarm;
    ModelRenderer tailbase;
    ModelRenderer lowertail;
    ModelRenderer uppertail;
    ModelRenderer upperrightleg;
    ModelRenderer lowerrightleg;
    ModelRenderer rightfoottoe1;
    ModelRenderer rightfoottoe2;
    ModelRenderer rightfoottoe3;
    ModelRenderer upperleftleg;
    ModelRenderer lowerleftleg;
    ModelRenderer leftfoottoe1;
    ModelRenderer leftfoottoe2;
    ModelRenderer leftfoottoe3;
  
  public ModelAbra()
  {
    textureWidth = 64;
    textureHeight = 32;
    
    BaseHead = new ModelRenderer(this, "BaseHead");
    BaseHead.setRotationPoint(0F, 16.5F, 3F);
    setRotation(BaseHead, 0F, 0F, 0F);
    BaseHead.mirror = true;
      ModelRenderer head = new ModelRenderer(this, 30, 0);
      head = new ModelRenderer(this, 30, 0);
      head.addBox(-2.5F, -4F, -2F, 5, 4, 4);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      BaseHead.addChild(head);
      ModelRenderer uppermuzzle = new ModelRenderer(this, 30, 8);
      uppermuzzle.addBox(-1.5F, -2.8F, -2.5F, 3, 1, 2);
      uppermuzzle.setRotationPoint(0F, 0F, 0F);
      uppermuzzle.setTextureSize(64, 32);
      uppermuzzle.mirror = true;
      setRotation(uppermuzzle, 0.6108652F, 0F, 0F);
      BaseHead.addChild(uppermuzzle);
      ModelRenderer lowermuzzle = new ModelRenderer(this, 30, 11);
      lowermuzzle.addBox(-1.5F, -1.2F, -3.5F, 3, 1, 2);
      lowermuzzle.setRotationPoint(0F, 0F, 0F);
      lowermuzzle.setTextureSize(64, 32);
      lowermuzzle.mirror = true;
      setRotation(lowermuzzle, 0.0872665F, 0F, 0F);
      BaseHead.addChild(lowermuzzle);
      ModelRenderer rightear = new ModelRenderer(this, 44, 0);
      rightear.addBox(-3F, -3F, 0F, 3, 3, 0);
      rightear.setRotationPoint(0F,0F, 0F);
      rightear.setTextureSize(64, 32);
      rightear.mirror = true;
      setRotation(rightear, 0.1396263F, -0.1396263F, 0F);
      BaseHead.addChild(rightear);
      ModelRenderer leftear = new ModelRenderer(this, 44, 0);
      leftear.addBox(-3F, -3F, 0F, 3, 3, 0);
      leftear.setRotationPoint(0F, 0F, 0F);
      leftear.setTextureSize(64, 32);
      leftear.mirror = true;
      setRotation(leftear, 0.1396263F, 0.1396263F, 1.570796F);
      BaseHead.addChild(leftear);
      ModelRenderer righteye = new ModelRenderer(this, 40, 11);
      righteye.addBox(-1.8F, -3.5F, 0.5F, 2, 1, 1);
      righteye.setRotationPoint(0F, 0F, 0F);
      righteye.setTextureSize(64, 32);
      righteye.mirror = true;
      setRotation(righteye, 0.7853982F, 0F, -0.0872665F);
      BaseHead.addChild(righteye);
      ModelRenderer lefteye = new ModelRenderer(this, 40, 11);
      lefteye = new ModelRenderer(this, 40, 11);
      lefteye.addBox(0.1F, -3.5F, 0.5F, 2, 1, 1);
      lefteye.setRotationPoint(0F, 0F, 0F);
      lefteye.setTextureSize(64, 32);
      lefteye.mirror = true;
      setRotation(lefteye, 0.7853982F, 0F, 0.0872665F);
      BaseHead.addChild(lefteye);
      neck = new ModelRenderer(this, 40, 8);
      neck.addBox(-1F, 0F, -1F, 2, 1, 2);
      neck.setRotationPoint(0F, 16F, 3F);
      neck.setTextureSize(64, 32);
      neck.mirror = true;
      setRotation(neck, 0F, 0F, 0F);
      finger1 = new ModelRenderer(this, 26, 0);
      finger1.addBox(-0.5F, -2F, -0.5F, 1, 2, 1);
      finger1.setRotationPoint(-1.2F, 20.4F, -2.4F);
      finger1.setTextureSize(64, 32);
      finger1.mirror = true;
      setRotation(finger1, -0.0698132F, 0.3490659F, 1.553343F);
      finger2 = new ModelRenderer(this, 26, 0);
      finger2.addBox(-0.5F, -2F, -0.5F, 1, 2, 1);
      finger2.setRotationPoint(1.7F, 21.6F, -2F);
      finger2.setTextureSize(64, 32);
      finger2.mirror = true;
      setRotation(finger2, -0.0698132F, -0.3665191F, -1.570796F);
      finger3 = new ModelRenderer(this, 26, 0);
      finger3.addBox(-0.5F, -2F, -0.5F, 1, 2, 1);
      finger3.setRotationPoint(-0.8F, 21.6F, -1F);
      finger3.setTextureSize(64, 32);
      finger3.mirror = true;
      setRotation(finger3, -0.0698132F, 0.1745329F, 1.570796F);
      upperbody = new ModelRenderer(this, 0, 0);
      upperbody.addBox(-2.5F, 0F, -2F, 5, 4, 4);
      upperbody.setRotationPoint(0F, 17F, 3F);
      upperbody.setTextureSize(64, 32);
      upperbody.mirror = true;
      setRotation(upperbody, 0F, 0F, 0F);
      lowerbody = new ModelRenderer(this, 0, 8);
      lowerbody.addBox(-2F, 0F, -1.5F, 4, 3, 3);
      lowerbody.setRotationPoint(0F, 21F, 3F);
      lowerbody.setTextureSize(64, 32);
      lowerbody.mirror = true;
      setRotation(lowerbody, 0F, 0F, 0F);
      rightshoulder = new ModelRenderer(this, 0, 20);
      rightshoulder.addBox(-2F, -1F, -1F, 2, 1, 2);
      rightshoulder.setRotationPoint(-2F, 18F, 3F);
      rightshoulder.setTextureSize(64, 32);
      rightshoulder.mirror = true;
      setRotation(rightshoulder, -0.9948377F, 0F, 0F);
      rightuppperarm = new ModelRenderer(this, 0, 14);
      rightuppperarm.addBox(-1F, -0.5F, -0.5F, 1, 5, 1);
      rightuppperarm.setRotationPoint(-2.5F, 18F, 3F);
      rightuppperarm.setTextureSize(64, 32);
      rightuppperarm.mirror = true;
      setRotation(rightuppperarm, -0.9948377F, 0F, 0F);
      rightlowerarm = new ModelRenderer(this, 8, 14);
      rightlowerarm.addBox(-1F, 0F, -1F, 2, 3, 2);
      rightlowerarm.setRotationPoint(-3F, 20.1F, -0.2F);
      rightlowerarm.setTextureSize(64, 32);
      rightlowerarm.mirror = true;
      setRotation(rightlowerarm, -0.0349066F, 0.6108652F, -1.27409F);
      leftshoulder = new ModelRenderer(this, 0, 23);
      leftshoulder.addBox(0F, -1F, -1F, 2, 1, 2);
      leftshoulder.setRotationPoint(2F, 18F, 3F);
      leftshoulder.setTextureSize(64, 32);
      leftshoulder.mirror = true;
      setRotation(leftshoulder, -0.9948377F, 0F, 0F);
      leftupperarm = new ModelRenderer(this, 4, 14);
      leftupperarm.addBox(0F, -0.5F, -0.5F, 1, 5, 1);
      leftupperarm.setRotationPoint(2.5F, 18F, 3F);
      leftupperarm.setTextureSize(64, 32);
      leftupperarm.mirror = true;
      setRotation(leftupperarm, -0.9948377F, 0F, 0F);
      leftlowerarm = new ModelRenderer(this, 8, 19);
      leftlowerarm.addBox(-1F, 0F, -1F, 2, 3, 2);
      leftlowerarm.setRotationPoint(3F, 20.1F, -0.2F);
      leftlowerarm.setTextureSize(64, 32);
      leftlowerarm.mirror = true;
      setRotation(leftlowerarm, -0.0349066F, -0.6108652F, 1.27409F);
      tailbase = new ModelRenderer(this, 54, 11);
      tailbase.addBox(-1.5F, -1.5F, 0F, 3, 3, 2);
      tailbase.setRotationPoint(0F, 22.5F, 4F);
      tailbase.setTextureSize(64, 32);
      tailbase.mirror = true;
      setRotation(tailbase, 0F, 0F, 0F);
      lowertail = new ModelRenderer(this, 52, 0);
      lowertail.addBox(-0.5F, 0F, -0.5F, 1, 4, 1);
      lowertail.setRotationPoint(5.5F, 17.5F, 6F);
      lowertail.setTextureSize(64, 32);
      lowertail.mirror = true;
      setRotation(lowertail, 0F, 0F, 3.141593F);
      uppertail = new ModelRenderer(this, 56, 0);
      uppertail.addBox(-1F, -1F, 0F, 2, 9, 2);
      uppertail.setRotationPoint(0F, 22.5F, 5F);
      uppertail.setTextureSize(64, 32);
      uppertail.mirror = true;
      setRotation(uppertail, 0F, 0F, -2.356194F);
      upperrightleg = new ModelRenderer(this, 18, 0);
      upperrightleg.addBox(-1F, -0.5F, -0.5F, 1, 4, 1);
      upperrightleg.setRotationPoint(-1.5F, 23F, 2F);
      upperrightleg.setTextureSize(64, 32);
      upperrightleg.mirror = true;
      setRotation(upperrightleg, -1.692969F, 0.4363323F, 0F);
      lowerrightleg = new ModelRenderer(this, 18, 5);
      lowerrightleg.addBox(-1F, -1F, -4F, 2, 2, 4);
      lowerrightleg.setRotationPoint(-3F, 22.5F, -0.5F);
      lowerrightleg.setTextureSize(64, 32);
      lowerrightleg.mirror = true;
      setRotation(lowerrightleg, 0.0698132F, 0.4363323F, 0F);
      rightfoottoe1 = new ModelRenderer(this, 26, 0);
      rightfoottoe1.addBox(-0.5F, -2F, -0.5F, 1, 2, 1);
      rightfoottoe1.setRotationPoint(-4F, 21.9F, -4F);
      rightfoottoe1.setTextureSize(64, 32);
      rightfoottoe1.mirror = true;
      setRotation(rightfoottoe1, 0.296706F, 0.4363323F, 0.5934119F);
      rightfoottoe2 = new ModelRenderer(this, 26, 0);
      rightfoottoe2.addBox(-0.5F, -2F, -0.5F, 1, 2, 1);
      rightfoottoe2.setRotationPoint(-5F, 21.9F, -3.5F);
      rightfoottoe2.setTextureSize(64, 32);
      rightfoottoe2.mirror = true;
      setRotation(rightfoottoe2, 0.296706F, 0.4363323F, -0.5934119F);
      rightfoottoe3 = new ModelRenderer(this, 26, 0);
      rightfoottoe3.addBox(-0.5F, -2F, -0.5F, 1, 2, 1);
      rightfoottoe3.setRotationPoint(-4.5F, 23.2F, -3.5F);
      rightfoottoe3.setTextureSize(64, 32);
      rightfoottoe3.mirror = true;
      setRotation(rightfoottoe3, 2.111848F, 0.4363323F, 0F);
      upperleftleg = new ModelRenderer(this, 22, 0);
      upperleftleg.addBox(0F, -0.5F, -0.5F, 1, 4, 1);
      upperleftleg.setRotationPoint(1.5F, 23F, 2F);
      upperleftleg.setTextureSize(64, 32);
      upperleftleg.mirror = true;
      setRotation(upperleftleg, -1.692969F, -0.4363323F, 0F);
      lowerleftleg = new ModelRenderer(this, 18, 11);
      lowerleftleg.addBox(-1F, -1F, -4F, 2, 2, 4);
      lowerleftleg.setRotationPoint(3F, 22.5F, -0.5F);
      lowerleftleg.setTextureSize(64, 32);
      lowerleftleg.mirror = true;
      setRotation(lowerleftleg, 0.0698132F, -0.4363323F, 0F);
      leftfoottoe1 = new ModelRenderer(this, 26, 0);
      leftfoottoe1.addBox(-0.5F, -2F, -0.5F, 1, 2, 1);
      leftfoottoe1.setRotationPoint(4F, 21.9F, -4F);
      leftfoottoe1.setTextureSize(64, 32);
      leftfoottoe1.mirror = true;
      setRotation(leftfoottoe1, 0.296706F, -0.4363323F, -0.5934119F);
      leftfoottoe2 = new ModelRenderer(this, 26, 0);
      leftfoottoe2.addBox(-0.5F, -2F, -0.5F, 1, 2, 1);
      leftfoottoe2.setRotationPoint(5F, 21.9F, -3.5F);
      leftfoottoe2.setTextureSize(64, 32);
      leftfoottoe2.mirror = true;
      setRotation(leftfoottoe2, 0.296706F, -0.4363323F, 0.5934119F);
      leftfoottoe3 = new ModelRenderer(this, 26, 0);
      leftfoottoe3.addBox(-0.5F, -2F, -0.5F, 1, 2, 1);
      leftfoottoe3.setRotationPoint(4.5F, 23.2F, -3.5F);
      leftfoottoe3.setTextureSize(64, 32);
      leftfoottoe3.mirror = true;
      setRotation(leftfoottoe3, 2.111848F, -0.4363323F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    BaseHead.render(f5);
    neck.render(f5);
    finger1.render(f5);
    finger2.render(f5);
    finger3.render(f5);
    upperbody.render(f5);
    lowerbody.render(f5);
    rightshoulder.render(f5);
    rightuppperarm.render(f5);
    rightlowerarm.render(f5);
    leftshoulder.render(f5);
    leftupperarm.render(f5);
    leftlowerarm.render(f5);
    tailbase.render(f5);
    lowertail.render(f5);
    uppertail.render(f5);
    upperrightleg.render(f5);
    lowerrightleg.render(f5);
    rightfoottoe1.render(f5);
    rightfoottoe2.render(f5);
    rightfoottoe3.render(f5);
    upperleftleg.render(f5);
    lowerleftleg.render(f5);
    leftfoottoe1.render(f5);
    leftfoottoe2.render(f5);
    leftfoottoe3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
