// Date: 08/05/2012 22:43:45
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package pixelmon.Pokemon;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelMagnemite extends ModelBase
{
  //fields
    ModelRenderer body;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape1;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
  
  public ModelMagnemite()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      body = new ModelRenderer(this, 0, 0);
      body.addBox(-2F, 0F, -2F, 5, 5, 5);
      body.setRotationPoint(0F, 13F, 0F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 34, 0);
      Shape2.addBox(0F, -2F, 0F, 1, 2, 1);
      Shape2.setRotationPoint(0F, 13F, 0F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 21, 0);
      Shape3.addBox(-1F, -3F, -1F, 3, 1, 3);
      Shape3.setRotationPoint(0F, 13F, 0F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 10);
      Shape4.addBox(-5F, 2F, 0F, 1, 1, 1);
      Shape4.setRotationPoint(-2F, 15F, 0F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 16);
      Shape5.addBox(-2F, 1F, 0F, 1, 1, 1);
      Shape5.setRotationPoint(-2F, 15F, 0F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 24);
      Shape6.addBox(-4F, -2F, 0F, 1, 1, 1);
      Shape6.setRotationPoint(-2F, 15F, 0F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 20);
      Shape7.addBox(-2F, -1F, 0F, 1, 1, 1);
      Shape7.setRotationPoint(-2F, 15F, 0F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 0, 18);
      Shape8.addBox(-1F, 0F, 0F, 1, 1, 1);
      Shape8.setRotationPoint(-2F, 15F, 0F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 0, 14);
      Shape9.addBox(-3F, 2F, 0F, 1, 1, 1);
      Shape9.setRotationPoint(-2F, 15F, 0F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 0, 26);
      Shape10.addBox(-5F, -2F, 0F, 1, 1, 1);
      Shape10.setRotationPoint(-2F, 15F, 0F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 0, 12);
      Shape11.addBox(-4F, 2F, 0F, 1, 1, 1);
      Shape11.setRotationPoint(-2F, 15F, 0F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 0, 22);
      Shape12.addBox(-3F, -2F, 0F, 1, 1, 1);
      Shape12.setRotationPoint(-2F, 15F, 0F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 5, 10);
      Shape13.addBox(4F, 2F, 0F, 1, 1, 1);
      Shape13.setRotationPoint(3F, 15F, 0F);
      Shape13.setTextureSize(64, 32);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 5, 26);
      Shape14.addBox(4F, -2F, 0F, 1, 1, 1);
      Shape14.setRotationPoint(3F, 15F, 0F);
      Shape14.setTextureSize(64, 32);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 5, 12);
      Shape15.addBox(3F, 2F, 0F, 1, 1, 1);
      Shape15.setRotationPoint(3F, 15F, 0F);
      Shape15.setTextureSize(64, 32);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 5, 24);
      Shape16.addBox(3F, -2F, 0F, 1, 1, 1);
      Shape16.setRotationPoint(3F, 15F, 0F);
      Shape16.setTextureSize(64, 32);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 5, 18);
      Shape17.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape17.setRotationPoint(3F, 15F, 0F);
      Shape17.setTextureSize(64, 32);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 5, 22);
      Shape18.addBox(2F, -2F, 0F, 1, 1, 1);
      Shape18.setRotationPoint(3F, 15F, 0F);
      Shape18.setTextureSize(64, 32);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 5, 20);
      Shape19.addBox(1F, -1F, 0F, 1, 1, 1);
      Shape19.setRotationPoint(3F, 15F, 0F);
      Shape19.setTextureSize(64, 32);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 5, 14);
      Shape20.addBox(2F, 2F, 0F, 1, 1, 1);
      Shape20.setRotationPoint(3F, 15F, 0F);
      Shape20.setTextureSize(64, 32);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 5, 16);
      Shape1.addBox(1F, 1F, 0F, 1, 1, 1);
      Shape1.setRotationPoint(3F, 15F, 0F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    body.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
    Shape19.render(f5);
    Shape20.render(f5);
    Shape1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
