// Date: 5/13/2012 1:32:13 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package pixelmon.Pokemon;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelMiltank extends ModelBase
{
  //fields
    ModelRenderer lefthorn;
    ModelRenderer righthorn;
    ModelRenderer leftear;
    ModelRenderer rightear;
    ModelRenderer head;
    ModelRenderer upperjaw;
    ModelRenderer lowerjaw;
    ModelRenderer upperbody;
    ModelRenderer midbody;
    ModelRenderer lowerbody;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer utter1;
    ModelRenderer utter2;
    ModelRenderer utter3;
    ModelRenderer utter4;
    ModelRenderer tailbase;
    ModelRenderer tailtip;
    ModelRenderer leftleg;
    ModelRenderer rightleg;
  
  public ModelMiltank()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      lefthorn = new ModelRenderer(this, 0, 30);
      lefthorn.addBox(-0.5F, -1F, -0.5F, 1, 1, 1);
      lefthorn.setRotationPoint(2F, 6F, 3F);
      lefthorn.setTextureSize(64, 64);
      lefthorn.mirror = true;
      setRotation(lefthorn, 0F, 0F, 0F);
      righthorn = new ModelRenderer(this, 0, 30);
      righthorn.addBox(-0.5F, -1F, -0.5F, 1, 1, 1);
      righthorn.setRotationPoint(-2F, 6F, 3F);
      righthorn.setTextureSize(64, 64);
      righthorn.mirror = true;
      setRotation(righthorn, 0F, 0F, 0F);
      leftear = new ModelRenderer(this, 6, 25);
      leftear.addBox(0F, 0F, -1.5F, 0, 5, 3);
      leftear.setRotationPoint(3F, 6F, 2F);
      leftear.setTextureSize(64, 64);
      leftear.mirror = true;
      setRotation(leftear, 0F, 0F, -0.5585054F);
      rightear = new ModelRenderer(this, 6, 25);
      rightear.addBox(0F, 0F, -1.5F, 0, 5, 3);
      rightear.setRotationPoint(-3F, 6F, 2F);
      rightear.setTextureSize(64, 64);
      rightear.mirror = true;
      setRotation(rightear, 0F, 0F, 0.5585054F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-3F, -6F, -2.5F, 6, 6, 5);
      head.setRotationPoint(0F, 12F, 1.5F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      upperjaw = new ModelRenderer(this, 0, 34);
      upperjaw.addBox(-2.5F, 0F, 0F, 5, 1, 4);
      upperjaw.setRotationPoint(0F, 10.1F, -4F);
      upperjaw.setTextureSize(64, 64);
      upperjaw.mirror = true;
      setRotation(upperjaw, 0.3490659F, 0F, 0F);
      lowerjaw = new ModelRenderer(this, 0, 40);
      lowerjaw.addBox(-2.5F, 0F, 0F, 5, 2, 4);
      lowerjaw.setRotationPoint(0F, 10.1F, -4F);
      lowerjaw.setTextureSize(64, 64);
      lowerjaw.mirror = true;
      setRotation(lowerjaw, 0.1047198F, 0F, 0F);
      upperbody = new ModelRenderer(this, 32, 0);
      upperbody.addBox(-4F, 0F, -4F, 8, 3, 7);
      upperbody.setRotationPoint(0F, 12F, 1.5F);
      upperbody.setTextureSize(64, 64);
      upperbody.mirror = true;
      setRotation(upperbody, 0F, 0F, 0F);
      midbody = new ModelRenderer(this, 28, 23);
      midbody.addBox(-4.5F, 2F, -5F, 9, 6, 8);
      midbody.setRotationPoint(0F, 12F, 1.5F);
      midbody.setTextureSize(64, 64);
      midbody.mirror = true;
      setRotation(midbody, 0F, 0F, 0F);
      lowerbody = new ModelRenderer(this, 32, 10);
      lowerbody.addBox(-4F, 3F, -4.5F, 8, 6, 7);
      lowerbody.setRotationPoint(0F, 12F, 1.5F);
      lowerbody.setTextureSize(64, 64);
      lowerbody.mirror = true;
      setRotation(lowerbody, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 22, 16);
      rightarm.addBox(-2F, -0.5F, -1F, 2, 5, 2);
      rightarm.setRotationPoint(-3.5F, 13.5F, 1F);
      rightarm.setTextureSize(64, 64);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0.8203047F);
      leftarm = new ModelRenderer(this, 22, 16);
      leftarm.addBox(0F, -0.5F, -1F, 2, 5, 2);
      leftarm.setRotationPoint(3.5F, 13.5F, 2F);
      leftarm.setTextureSize(64, 64);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, -0.8203047F);
      utter1 = new ModelRenderer(this, 6, 9);
      utter1.addBox(-2F, 3.5F, -5.5F, 1, 1, 1);
      utter1.setRotationPoint(0F, 12.5F, 1.5F);
      utter1.setTextureSize(64, 64);
      utter1.mirror = true;
      setRotation(utter1, 0F, 0F, 0F);
      utter2 = new ModelRenderer(this, 6, 9);
      utter2.addBox(-2F, 6F, -5.5F, 1, 1, 1);
      utter2.setRotationPoint(0F, 12.5F, 1.5F);
      utter2.setTextureSize(64, 64);
      utter2.mirror = true;
      setRotation(utter2, 0F, 0F, 0F);
      utter3 = new ModelRenderer(this, 6, 9);
      utter3.addBox(1F, 3.5F, -5.5F, 1, 1, 1);
      utter3.setRotationPoint(0F, 12.5F, 1.5F);
      utter3.setTextureSize(64, 64);
      utter3.mirror = true;
      setRotation(utter3, 0F, 0F, 0F);
      utter4 = new ModelRenderer(this, 6, 9);
      utter4.addBox(1F, 6F, -5.5F, 1, 1, 1);
      utter4.setRotationPoint(0F, 12.5F, 1.5F);
      utter4.setTextureSize(64, 64);
      utter4.mirror = true;
      setRotation(utter4, 0F, 0F, 0F);
      tailbase = new ModelRenderer(this, 46, 33);
      tailbase.addBox(0F, -9F, -2F, 0, 9, 8);
      tailbase.setRotationPoint(0F, 20F, 4F);
      tailbase.setTextureSize(64, 64);
      tailbase.mirror = true;
      setRotation(tailbase, 0F, 0F, 0F);
      tailtip = new ModelRenderer(this, 0, 48);
      tailtip.addBox(-1F, -2F, -1F, 2, 2, 2);
      tailtip.setRotationPoint(0F, 12F, 9.5F);
      tailtip.setTextureSize(64, 64);
      tailtip.mirror = true;
      setRotation(tailtip, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(0F, -1F, -2F, 3, 6, 4);
      leftleg.setRotationPoint(3F, 19F, 1F);
      leftleg.setTextureSize(64, 64);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-3F, -1F, -2F, 3, 6, 4);
      rightleg.setRotationPoint(-3F, 19F, 1F);
      rightleg.setTextureSize(64, 64);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    lefthorn.render(f5);
    righthorn.render(f5);
    leftear.render(f5);
    rightear.render(f5);
    head.render(f5);
    upperjaw.render(f5);
    lowerjaw.render(f5);
    upperbody.render(f5);
    midbody.render(f5);
    lowerbody.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    utter1.render(f5);
    utter2.render(f5);
    utter3.render(f5);
    utter4.render(f5);
    tailbase.render(f5);
    tailtip.render(f5);
    leftleg.render(f5);
    rightleg.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
