package pixelmon.Pokemon;

import net.minecraft.src.Entity;
import net.minecraft.src.MathHelper;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelFlareon extends ModelBase
{
  //fields
    ModelRenderer EarLeft;
    ModelRenderer EarTipLeft;
    ModelRenderer EarRight;
    ModelRenderer EarTipRight;
    ModelRenderer FluffBase;
    ModelRenderer FluffSeg1;
    ModelRenderer FluffSeg2;
    ModelRenderer FluffTip;
    ModelRenderer Head;
    ModelRenderer Nose;
    ModelRenderer ManeRightAngle;
    ModelRenderer ManeLeftAngle;
    ModelRenderer Body;
    ModelRenderer TailBase;
    ModelRenderer TailSeg1;
    ModelRenderer TailSeg2;
    ModelRenderer TailSeg3;
    ModelRenderer TailSeg4;
    ModelRenderer TailSeg5;
    ModelRenderer TailSeg6;
    ModelRenderer RearUpperLeftLeg;
    ModelRenderer RearKneeLeft;
    ModelRenderer RearlowerLeftLeg;
    ModelRenderer RearToesLeft;
    ModelRenderer RearUpperRightLeg;
    ModelRenderer RearKneeRight;
    ModelRenderer RearlowerRightLeg;
    ModelRenderer RearToesRight;
    ModelRenderer FrontRightLeg;
    ModelRenderer FrontToesRight;
    ModelRenderer FrontLeftLeg;
    ModelRenderer FrontToesLeft;
  
  public ModelFlareon()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      EarLeft = new ModelRenderer(this, 16, 6);
      EarLeft.addBox(-1.5F, -5F, -1.4F, 2, 3, 1);
      EarLeft.setRotationPoint(0F, 16.5F, -4.4F);
      EarLeft.setTextureSize(64, 32);
      EarLeft.mirror = true;
      setRotation(EarLeft, -0.0523599F, -0.0872665F, 0.6981317F);
      EarLeft.mirror = false;
      EarTipLeft = new ModelRenderer(this, 17, 4);
      EarTipLeft.addBox(0F, -6F, -1.4F, 1, 1, 1);
      EarTipLeft.setRotationPoint(0F, 16.5F, -4.4F);
      EarTipLeft.setTextureSize(64, 32);
      EarTipLeft.mirror = true;
      setRotation(EarTipLeft, -0.0523599F, 0.0872665F, -0.6981317F);
      EarRight = new ModelRenderer(this, 16, 6);
      EarRight.addBox(-0.5F, -5F, -1.4F, 2, 3, 1);
      EarRight.setRotationPoint(0F, 16.5F, -4.4F);
      EarRight.setTextureSize(64, 32);
      EarRight.mirror = true;
      setRotation(EarRight, -0.0523599F, 0.0872665F, -0.6981317F);
      EarTipRight = new ModelRenderer(this, 17, 4);
      EarTipRight.addBox(-1F, -6F, -1.4F, 1, 1, 1);
      EarTipRight.setRotationPoint(0F, 16.5F, -4.4F);
      EarTipRight.setTextureSize(64, 32);
      EarTipRight.mirror = true;
      setRotation(EarTipRight, -0.0523599F, -0.0872665F, 0.6981317F);
      FluffBase = new ModelRenderer(this, 52, 29);
      FluffBase.addBox(-1F, -3.7F, -2.5F, 2, 1, 2);
      FluffBase.setRotationPoint(0F, 16.5F, -4.4F);
      FluffBase.setTextureSize(64, 32);
      FluffBase.mirror = true;
      setRotation(FluffBase, 0F, 0F, 0F);
      FluffSeg1 = new ModelRenderer(this, 52, 29);
      FluffSeg1.addBox(-1F, -4.3F, -2F, 2, 1, 2);
      FluffSeg1.setRotationPoint(0F, 16.5F, -4.4F);
      FluffSeg1.setTextureSize(64, 32);
      FluffSeg1.mirror = true;
      setRotation(FluffSeg1, 0F, 0F, 0F);
      FluffSeg2 = new ModelRenderer(this, 52, 29);
      FluffSeg2.addBox(-1F, -4.7F, -0.8F, 2, 1, 1);
      FluffSeg2.setRotationPoint(0F, 16.5F, -4.4F);
      FluffSeg2.setTextureSize(64, 32);
      FluffSeg2.mirror = true;
      setRotation(FluffSeg2, 0F, 0F, 0F);
      FluffTip = new ModelRenderer(this, 52, 29);
      FluffTip.addBox(-0.5F, -5.1F, -0.3F, 1, 1, 1);
      FluffTip.setRotationPoint(0F, 16.5F, -4.4F);
      FluffTip.setTextureSize(64, 32);
      FluffTip.mirror = true;
      setRotation(FluffTip, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 0, 3);
      Head.addBox(-2F, -3F, -3F, 4, 4, 3);
      Head.setRotationPoint(0F, 16.5F, -4.4F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0.0872665F, 0F, 0F);
      Nose = new ModelRenderer(this, 0, 0);
      Nose.addBox(-1.5F, -1.3F, -3.5F, 3, 2, 1);
      Nose.setRotationPoint(0F, 16.5F, -4.4F);
      Nose.setTextureSize(64, 32);
      Nose.mirror = true;
      setRotation(Nose, 0.2094395F, 0F, 0F);
      ManeRightAngle = new ModelRenderer(this, 0, 10);
      ManeRightAngle.addBox(-3.5F, -3.5F, -4F, 7, 6, 4);
      ManeRightAngle.setRotationPoint(0F, 18F, -1.2F);
      ManeRightAngle.setTextureSize(64, 32);
      ManeRightAngle.mirror = true;
      setRotation(ManeRightAngle, -0.122173F, -0.0174533F, -0.1745329F);
      ManeRightAngle.mirror = false;
      ManeLeftAngle = new ModelRenderer(this, 0, 10);
      ManeLeftAngle.addBox(-3.5F, -3.5F, -4F, 7, 6, 4);
      ManeLeftAngle.setRotationPoint(0F, 18F, -1.2F);
      ManeLeftAngle.setTextureSize(64, 32);
      ManeLeftAngle.mirror = true;
      setRotation(ManeLeftAngle, -0.122173F, 0.0174533F, 0.1745329F);
      Body = new ModelRenderer(this, 0, 20);
      Body.addBox(-2.5F, -3F, -4.4F, 5, 4, 8);
      Body.setRotationPoint(0F, 18.5F, 2F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      TailBase = new ModelRenderer(this, 52, 28);
      TailBase.addBox(-1.5F, -1.5F, 0F, 3, 3, 1);
      TailBase.setRotationPoint(0F, 17.1F, 5F);
      TailBase.setTextureSize(64, 32);
      TailBase.mirror = true;
      setRotation(TailBase, 0F, 0F, 0F);
      TailSeg1 = new ModelRenderer(this, 51, 26);
      TailSeg1.addBox(-2F, -1.7F, 0.7F, 4, 4, 2);
      TailSeg1.setRotationPoint(0F, 17.1F, 5F);
      TailSeg1.setTextureSize(64, 32);
      TailSeg1.mirror = true;
      setRotation(TailSeg1, 0.1570796F, 0F, 0F);
      TailSeg2 = new ModelRenderer(this, 50, 25);
      TailSeg2.addBox(-2.5F, -1.8F, 1.5F, 5, 5, 2);
      TailSeg2.setRotationPoint(0F, 17.1F, 5F);
      TailSeg2.setTextureSize(64, 32);
      TailSeg2.mirror = true;
      setRotation(TailSeg2, 0.3665191F, 0F, 0F);
      TailSeg3 = new ModelRenderer(this, 50, 26);
      TailSeg3.addBox(-2F, -0.7F, 2.4F, 4, 4, 2);
      TailSeg3.setRotationPoint(0F, 17.1F, 5F);
      TailSeg3.setTextureSize(64, 32);
      TailSeg3.mirror = true;
      setRotation(TailSeg3, 0.5759587F, 0F, 0F);
      TailSeg4 = new ModelRenderer(this, 51, 27);
      TailSeg4.addBox(-1.5F, 0.5F, 3.5F, 3, 3, 2);
      TailSeg4.setRotationPoint(0F, 17.1F, 5F);
      TailSeg4.setTextureSize(64, 32);
      TailSeg4.mirror = true;
      setRotation(TailSeg4, 0.7853982F, 0F, 0F);
      TailSeg5 = new ModelRenderer(this, 51, 28);
      TailSeg5.addBox(-1F, 2F, 4.3F, 2, 2, 2);
      TailSeg5.setRotationPoint(0F, 17.1F, 5F);
      TailSeg5.setTextureSize(64, 32);
      TailSeg5.mirror = true;
      setRotation(TailSeg5, 1.012291F, 0F, 0F);
      TailSeg6 = new ModelRenderer(this, 51, 28);
      TailSeg6.addBox(-0.5F, 3.9F, 4.5F, 1, 1, 2);
      TailSeg6.setRotationPoint(0F, 17.1F, 5F);
      TailSeg6.setTextureSize(64, 32);
      TailSeg6.mirror = true;
      setRotation(TailSeg6, 1.27409F, 0F, 0F);
      RearUpperLeftLeg = new ModelRenderer(this, 52, 0);
      RearUpperLeftLeg.addBox(0F, -0.5F, -1.5F, 2, 4, 3);
      RearUpperLeftLeg.setRotationPoint(0.6F, 17F, 4F);
      RearUpperLeftLeg.setTextureSize(64, 32);
      RearUpperLeftLeg.mirror = true;
      setRotation(RearUpperLeftLeg, 0.0872665F, 0F, 0F);
      RearUpperLeftLeg.mirror = false;
      RearKneeLeft = new ModelRenderer(this, 8, 1);
      RearKneeLeft.addBox(0F, 1.7F, -3.3F, 2, 1, 1);
      RearKneeLeft.setRotationPoint(0.6F, 17F, 4F);
      RearKneeLeft.setTextureSize(64, 32);
      RearKneeLeft.mirror = true;
      setRotation(RearKneeLeft, 0.7853982F, 0F, 0F);
      RearKneeLeft.mirror = false;
      RearlowerLeftLeg = new ModelRenderer(this, 52, 0);
      RearlowerLeftLeg.addBox(0F, 2.9F, 0.4F, 2, 4, 2);
      RearlowerLeftLeg.setRotationPoint(0.6F, 17F, 4F);
      RearlowerLeftLeg.setTextureSize(64, 32);
      RearlowerLeftLeg.mirror = true;
      setRotation(RearlowerLeftLeg, -0.1919862F, 0F, 0F);
      RearlowerLeftLeg.mirror = false;
      RearToesLeft = new ModelRenderer(this, 8, 1);
      RearToesLeft.addBox(0F, 6F, -1.3F, 2, 1, 1);
      RearToesLeft.setRotationPoint(0.6F, 17F, 4F);
      RearToesLeft.setTextureSize(64, 32);
      RearToesLeft.mirror = true;
      setRotation(RearToesLeft, 0F, 0F, 0F);
      RearToesLeft.mirror = false;
      RearUpperRightLeg = new ModelRenderer(this, 52, 0);
      RearUpperRightLeg.addBox(-2F, -0.5F, -1.5F, 2, 4, 3);
      RearUpperRightLeg.setRotationPoint(-0.6F, 17F, 4F);
      RearUpperRightLeg.setTextureSize(64, 32);
      RearUpperRightLeg.mirror = true;
      setRotation(RearUpperRightLeg, 0.0872665F, 0F, 0F);
      RearKneeRight = new ModelRenderer(this, 8, 1);
      RearKneeRight.addBox(-2F, 1.7F, -3.3F, 2, 1, 1);
      RearKneeRight.setRotationPoint(-0.6F, 17F, 4F);
      RearKneeRight.setTextureSize(64, 32);
      RearKneeRight.mirror = true;
      setRotation(RearKneeRight, 0.7853982F, 0F, 0F);
      RearlowerRightLeg = new ModelRenderer(this, 52, 0);
      RearlowerRightLeg.addBox(-2F, 2.9F, 0.4F, 2, 4, 2);
      RearlowerRightLeg.setRotationPoint(-0.6F, 17F, 4F);
      RearlowerRightLeg.setTextureSize(64, 32);
      RearlowerRightLeg.mirror = true;
      setRotation(RearlowerRightLeg, -0.2094395F, 0F, 0F);
      RearToesRight = new ModelRenderer(this, 8, 1);
      RearToesRight.addBox(-2F, 6F, -1.3F, 2, 1, 1);
      RearToesRight.setRotationPoint(-0.6F, 17F, 4F);
      RearToesRight.setTextureSize(64, 32);
      RearToesRight.mirror = true;
      setRotation(RearToesRight, 0F, 0F, 0F);
      FrontRightLeg = new ModelRenderer(this, 52, 0);
      FrontRightLeg.addBox(-1F, 0F, -1F, 2, 4, 2);
      FrontRightLeg.setRotationPoint(-2F, 20F, -3F);
      FrontRightLeg.setTextureSize(64, 32);
      FrontRightLeg.mirror = true;
      setRotation(FrontRightLeg, 0F, 0F, 0F);
      FrontToesRight = new ModelRenderer(this, 8, 1);
      FrontToesRight.addBox(-1F, 4F, -1.5F, 2, 1, 1);
      FrontToesRight.setRotationPoint(-2F, 19F, -3F);
      FrontToesRight.setTextureSize(64, 32);
      FrontToesRight.mirror = true;
      setRotation(FrontToesRight, 0F, 0F, 0F);
      FrontLeftLeg = new ModelRenderer(this, 52, 0);
      FrontLeftLeg.addBox(-1F, 0F, -1F, 2, 4, 2);
      FrontLeftLeg.setRotationPoint(2F, 20F, -3F);
      FrontLeftLeg.setTextureSize(64, 32);
      FrontLeftLeg.mirror = true;
      setRotation(FrontLeftLeg, 0F, 0F, 0F);
      FrontLeftLeg.mirror = false;
      FrontToesLeft = new ModelRenderer(this, 8, 1);
      FrontToesLeft.addBox(-1F, 4F, -1.5F, 2, 1, 1);
      FrontToesLeft.setRotationPoint(2F, 19F, -3F);
      FrontToesLeft.setTextureSize(64, 32);
      FrontToesLeft.mirror = true;
      setRotation(FrontToesLeft, 0F, 0F, 0F);
      FrontToesLeft.mirror = false;
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    EarLeft.render(f5);
    EarTipLeft.render(f5);
    EarRight.render(f5);
    EarTipRight.render(f5);
    FluffBase.render(f5);
    FluffSeg1.render(f5);
    FluffSeg2.render(f5);
    FluffTip.render(f5);
    Head.render(f5);
    Nose.render(f5);
    ManeRightAngle.render(f5);
    ManeLeftAngle.render(f5);
    Body.render(f5);
    TailBase.render(f5);
    TailSeg1.render(f5);
    TailSeg2.render(f5);
    TailSeg3.render(f5);
    TailSeg4.render(f5);
    TailSeg5.render(f5);
    TailSeg6.render(f5);
    RearUpperLeftLeg.render(f5);
    RearKneeLeft.render(f5);
    RearlowerLeftLeg.render(f5);
    RearToesLeft.render(f5);
    RearUpperRightLeg.render(f5);
    RearKneeRight.render(f5);
    RearlowerRightLeg.render(f5);
    RearToesRight.render(f5);
    FrontRightLeg.render(f5);
    FrontToesRight.render(f5);
    FrontLeftLeg.render(f5);
    FrontToesLeft.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
