package pixelmon.Pokemon;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelJolteon extends ModelBase
{
  //fields
    ModelRenderer EarR;
    ModelRenderer EarL;
    ModelRenderer Head;
    ModelRenderer Muzzle;
    ModelRenderer Nose;
    ModelRenderer Jaw;
    ModelRenderer Chest;
    ModelRenderer LowerBody;
    ModelRenderer FrontUpperLegR;
    ModelRenderer FrontLowerLegR;
    ModelRenderer FrontPawR;
    ModelRenderer FrontUpperLegL;
    ModelRenderer FrontLowerLegL;
    ModelRenderer FrontPawL;
    ModelRenderer RearUpperLegR;
    ModelRenderer RearLegJointR;
    ModelRenderer RearLowerLegR;
    ModelRenderer RearPawR;
    ModelRenderer RearUpperLegL;
    ModelRenderer RearLegJointL;
    ModelRenderer RearLowerLegL;
    ModelRenderer RearPawL;
    ModelRenderer CollarSpikelow;
    ModelRenderer CollarSpikeRight;
    ModelRenderer CollarSpikeLeft;
    ModelRenderer CollarSpikeHigh;
    ModelRenderer CollarSpikeLowRight;
    ModelRenderer CollarSpikeLowLeft;
    ModelRenderer CollarSpikelowLeftBetween;
    ModelRenderer CollarSpikelowRightBetween;
    ModelRenderer CollarSpikeRightBetween;
    ModelRenderer CollarSpikeLeftBetween;
    ModelRenderer CollarSpikeTopRightBetween;
    ModelRenderer CollarSpikeTopLeftBetween;
    ModelRenderer SideLowerSpikeRight;
    ModelRenderer SideUpperSpikeRight;
    ModelRenderer RearSpikeRight;
    ModelRenderer RearSpikeTopRight;
    ModelRenderer RearSpikeTop;
    ModelRenderer SideLowerSpikeLeft;
    ModelRenderer SideUpperSpikeLeft;
    ModelRenderer RearSpikeLeft;
    ModelRenderer RearSpikeTopLeft;
  
  public ModelJolteon()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      EarR = new ModelRenderer(this, 0, 4);
      EarR.addBox(-0.5F, -3F, 0F, 1, 3, 0);
      EarR.setRotationPoint(-0.8F, 14F, -4.8F);
      EarR.setTextureSize(64, 32);
      EarR.mirror = true;
      setRotation(EarR, 0F, 0.3490659F, -0.4363323F);
      EarL = new ModelRenderer(this, 0, 4);
      EarL.addBox(-0.5F, -3F, 0F, 1, 3, 0);
      EarL.setRotationPoint(0.8F, 14F, -4.8F);
      EarL.setTextureSize(64, 32);
      EarL.mirror = true;
      setRotation(EarL, 0F, -0.3490659F, 0.4363323F);
      Head = new ModelRenderer(this, 0, 9);
      Head.addBox(-1.5F, -2F, -3F, 3, 3, 3);
      Head.setRotationPoint(0F, 15.6F, -3.8F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0.0349066F, 0F, 0F);
      Muzzle = new ModelRenderer(this, 0, 7);
      Muzzle.addBox(-1F, -0.5F, -1F, 2, 1, 1);
      Muzzle.setRotationPoint(0F, 15.5F, -6.8F);
      Muzzle.setTextureSize(64, 32);
      Muzzle.mirror = true;
      setRotation(Muzzle, 0.0872665F, 0F, 0F);
      Nose = new ModelRenderer(this, 2, 0);
      Nose.addBox(-0.5F, -0.5F, -1F, 1, 1, 1);
      Nose.setRotationPoint(0F, 15.4F, -6.8F);
      Nose.setTextureSize(64, 32);
      Nose.mirror = true;
      setRotation(Nose, 0.2617994F, 0F, 0F);
      Jaw = new ModelRenderer(this, 0, 7);
      Jaw.addBox(-1F, -0.5F, -1F, 2, 1, 1);
      Jaw.setRotationPoint(0F, 16.1F, -6.7F);
      Jaw.setTextureSize(64, 32);
      Jaw.mirror = true;
      setRotation(Jaw, 0.0349066F, 0F, 0F);
      Chest = new ModelRenderer(this, 0, 15);
      Chest.addBox(-2F, -2.5F, -4F, 4, 4, 4);
      Chest.setRotationPoint(0F, 17.9F, -0.7F);
      Chest.setTextureSize(64, 32);
      Chest.mirror = true;
      setRotation(Chest, -0.122173F, 0F, 0F);
      LowerBody = new ModelRenderer(this, 0, 23);
      LowerBody.addBox(-2F, -1.5F, -3F, 4, 3, 6);
      LowerBody.setRotationPoint(0F, 17.4F, 1.7F);
      LowerBody.setTextureSize(64, 32);
      LowerBody.mirror = true;
      setRotation(LowerBody, 0F, 0F, 0F);
      FrontUpperLegR = new ModelRenderer(this, 56, 27);
      FrontUpperLegR.addBox(-2F, -1F, -1F, 2, 3, 2);
      FrontUpperLegR.setRotationPoint(-0.5F, 17.7F, -3.2F);
      FrontUpperLegR.setTextureSize(64, 32);
      FrontUpperLegR.mirror = true;
      setRotation(FrontUpperLegR, 0.0872665F, 0F, -0.0174533F);
      FrontLowerLegR = new ModelRenderer(this, 60, 11);
      FrontLowerLegR.addBox(-0.5F, 0F, -0.5F, 1, 5, 1);
      FrontLowerLegR.setRotationPoint(-1.5F, 19.1F, -3.3F);
      FrontLowerLegR.setTextureSize(64, 32);
      FrontLowerLegR.mirror = true;
      setRotation(FrontLowerLegR, -0.0349066F, 0F, 0F);
      FrontPawR = new ModelRenderer(this, 60, 9);
      FrontPawR.addBox(-0.5F, 0F, -1F, 1, 1, 1);
      FrontPawR.setRotationPoint(-1.5F, 23F, -3.2F);
      FrontPawR.setTextureSize(64, 32);
      FrontPawR.mirror = true;
      setRotation(FrontPawR, 0F, 0F, 0F);
      FrontUpperLegL = new ModelRenderer(this, 56, 27);
      FrontUpperLegL.addBox(0F, -1F, -1F, 2, 3, 2);
      FrontUpperLegL.setRotationPoint(0.5F, 17.7F, -3.2F);
      FrontUpperLegL.setTextureSize(64, 32);
      FrontUpperLegL.mirror = true;
      setRotation(FrontUpperLegL, 0.0872665F, 0F, 0.0174533F);
      FrontLowerLegL = new ModelRenderer(this, 60, 11);
      FrontLowerLegL.addBox(-0.5F, 0F, -0.5F, 1, 5, 1);
      FrontLowerLegL.setRotationPoint(1.5F, 19.1F, -3.3F);
      FrontLowerLegL.setTextureSize(64, 32);
      FrontLowerLegL.mirror = true;
      setRotation(FrontLowerLegL, -0.0349066F, 0F, 0F);
      FrontPawL = new ModelRenderer(this, 60, 9);
      FrontPawL.addBox(-0.5F, 0F, -1F, 1, 1, 1);
      FrontPawL.setRotationPoint(1.5F, 23F, -3.2F);
      FrontPawL.setTextureSize(64, 32);
      FrontPawL.mirror = true;
      setRotation(FrontPawL, 0F, 0F, 0F);
      RearUpperLegR = new ModelRenderer(this, 54, 21);
      RearUpperLegR.addBox(-2F, -1F, -1.5F, 2, 3, 3);
      RearUpperLegR.setRotationPoint(-0.5F, 17.5F, 3.3F);
      RearUpperLegR.setTextureSize(64, 32);
      RearUpperLegR.mirror = true;
      setRotation(RearUpperLegR, 0.1745329F, 0F, 0F);
      RearLegJointR = new ModelRenderer(this, 58, 17);
      RearLegJointR.addBox(-0.5F, 0F, -1F, 1, 2, 2);
      RearLegJointR.setRotationPoint(-1.5F, 18.6F, 2.9F);
      RearLegJointR.setTextureSize(64, 32);
      RearLegJointR.mirror = true;
      setRotation(RearLegJointR, 0.837758F, 0F, 0F);
      RearLowerLegR = new ModelRenderer(this, 60, 11);
      RearLowerLegR.addBox(-0.5F, -1F, 0F, 1, 5, 1);
      RearLowerLegR.setRotationPoint(-1.5F, 19.9F, 3.8F);
      RearLowerLegR.setTextureSize(64, 32);
      RearLowerLegR.mirror = true;
      setRotation(RearLowerLegR, -0.2617994F, 0F, 0F);
      RearPawR = new ModelRenderer(this, 60, 9);
      RearPawR.addBox(-0.5F, 0F, -1F, 1, 1, 1);
      RearPawR.setRotationPoint(-1.5F, 23F, 3.7F);
      RearPawR.setTextureSize(64, 32);
      RearPawR.mirror = true;
      setRotation(RearPawR, 0F, 0F, 0F);
      RearUpperLegL = new ModelRenderer(this, 54, 21);
      RearUpperLegL.addBox(0F, -1F, -1.5F, 2, 3, 3);
      RearUpperLegL.setRotationPoint(0.5F, 17.5F, 3.3F);
      RearUpperLegL.setTextureSize(64, 32);
      RearUpperLegL.mirror = true;
      setRotation(RearUpperLegL, 0.1745329F, 0F, 0.0174533F);
      RearLegJointL = new ModelRenderer(this, 58, 17);
      RearLegJointL.addBox(-0.5F, 0F, -1F, 1, 2, 2);
      RearLegJointL.setRotationPoint(1.5F, 18.6F, 2.9F);
      RearLegJointL.setTextureSize(64, 32);
      RearLegJointL.mirror = true;
      setRotation(RearLegJointL, 0.837758F, 0F, 0F);
      RearLowerLegL = new ModelRenderer(this, 60, 11);
      RearLowerLegL.addBox(-0.5F, -1F, 0F, 1, 5, 1);
      RearLowerLegL.setRotationPoint(1.5F, 19.9F, 3.8F);
      RearLowerLegL.setTextureSize(64, 32);
      RearLowerLegL.mirror = true;
      setRotation(RearLowerLegL, -0.2617994F, 0F, 0F);
      RearPawL = new ModelRenderer(this, 60, 9);
      RearPawL.addBox(-0.5F, 0F, -1F, 1, 1, 1);
      RearPawL.setRotationPoint(1.5F, 23F, 3.7F);
      RearPawL.setTextureSize(64, 32);
      RearPawL.mirror = true;
      setRotation(RearPawL, 0F, 0F, 0F);
      CollarSpikelow = new ModelRenderer(this, 0, 0);
      CollarSpikelow.addBox(-0.5F, 0F, 0F, 1, 3, 0);
      CollarSpikelow.setRotationPoint(0F, 16.6F, -4.9F);
      CollarSpikelow.setTextureSize(64, 32);
      CollarSpikelow.mirror = true;
      setRotation(CollarSpikelow, -0.0872665F, 0F, 0F);
      CollarSpikeRight = new ModelRenderer(this, 0, 0);
      CollarSpikeRight.addBox(-0.5F, 0F, 0F, 1, 3, 0);
      CollarSpikeRight.setRotationPoint(-0.8F, 15.9F, -4.5F);
      CollarSpikeRight.setTextureSize(64, 32);
      CollarSpikeRight.mirror = true;
      setRotation(CollarSpikeRight, -1.832596F, 2.129302F, 0.8726646F);
      CollarSpikeLeft = new ModelRenderer(this, 0, 0);
      CollarSpikeLeft.addBox(-0.5F, 0F, 0F, 1, 3, 0);
      CollarSpikeLeft.setRotationPoint(0.8F, 15.9F, -4.5F);
      CollarSpikeLeft.setTextureSize(64, 32);
      CollarSpikeLeft.mirror = true;
      setRotation(CollarSpikeLeft, -1.832596F, -2.129302F, -0.8726646F);
      CollarSpikeHigh = new ModelRenderer(this, 0, 0);
      CollarSpikeHigh.addBox(-0.5F, 0F, 0F, 1, 3, 0);
      CollarSpikeHigh.setRotationPoint(0F, 15.1F, -4F);
      CollarSpikeHigh.setTextureSize(64, 32);
      CollarSpikeHigh.mirror = true;
      setRotation(CollarSpikeHigh, 2.094395F, 0F, 0F);
      CollarSpikeLowRight = new ModelRenderer(this, 0, 0);
      CollarSpikeLowRight.addBox(-0.5F, 0F, 0F, 1, 3, 0);
      CollarSpikeLowRight.setRotationPoint(-0.5F, 16.2F, -4.8F);
      CollarSpikeLowRight.setTextureSize(64, 32);
      CollarSpikeLowRight.mirror = true;
      setRotation(CollarSpikeLowRight, -0.1919862F, 0.3141593F, 0.7679449F);
      CollarSpikeLowRight.mirror = false;
      CollarSpikeLowLeft = new ModelRenderer(this, 0, 0);
      CollarSpikeLowLeft.addBox(-0.5F, 0F, 0F, 1, 3, 0);
      CollarSpikeLowLeft.setRotationPoint(0.5F, 16.2F, -4.8F);
      CollarSpikeLowLeft.setTextureSize(64, 32);
      CollarSpikeLowLeft.mirror = true;
      setRotation(CollarSpikeLowLeft, -0.1919862F, -0.3141593F, -0.7679449F);
      CollarSpikelowLeftBetween = new ModelRenderer(this, 0, 0);
      CollarSpikelowLeftBetween.addBox(-0.5F, 0F, 0F, 1, 2, 0);
      CollarSpikelowLeftBetween.setRotationPoint(-0.3F, 16.6F, -4.8F);
      CollarSpikelowLeftBetween.setTextureSize(64, 32);
      CollarSpikelowLeftBetween.mirror = true;
      setRotation(CollarSpikelowLeftBetween, -0.1745329F, 0.1745329F, 0.418879F);
      CollarSpikelowRightBetween = new ModelRenderer(this, 0, 0);
      CollarSpikelowRightBetween.addBox(-0.5F, 0F, 0F, 1, 2, 0);
      CollarSpikelowRightBetween.setRotationPoint(0.3F, 16.6F, -4.8F);
      CollarSpikelowRightBetween.setTextureSize(64, 32);
      CollarSpikelowRightBetween.mirror = true;
      setRotation(CollarSpikelowRightBetween, -0.1745329F, -0.1745329F, -0.418879F);
      CollarSpikeRightBetween = new ModelRenderer(this, 0, 0);
      CollarSpikeRightBetween.addBox(-0.5F, 0F, 0F, 1, 2, 0);
      CollarSpikeRightBetween.setRotationPoint(-0.8F, 16.6F, -4.8F);
      CollarSpikeRightBetween.setTextureSize(64, 32);
      CollarSpikeRightBetween.mirror = true;
      setRotation(CollarSpikeRightBetween, -1.361357F, 1.605703F, 1.343904F);
      CollarSpikeLeftBetween = new ModelRenderer(this, 0, 0);
      CollarSpikeLeftBetween.addBox(-0.5F, 0F, 0F, 1, 2, 0);
      CollarSpikeLeftBetween.setRotationPoint(0.8F, 16.6F, -4.8F);
      CollarSpikeLeftBetween.setTextureSize(64, 32);
      CollarSpikeLeftBetween.mirror = true;
      setRotation(CollarSpikeLeftBetween, -1.361357F, -1.605703F, -1.343904F);
      CollarSpikeTopRightBetween = new ModelRenderer(this, 0, 0);
      CollarSpikeTopRightBetween.addBox(0F, 0F, -0.5F, 0, 2, 1);
      CollarSpikeTopRightBetween.setRotationPoint(-0.8F, 15.2F, -4F);
      CollarSpikeTopRightBetween.setTextureSize(64, 32);
      CollarSpikeTopRightBetween.mirror = true;
      setRotation(CollarSpikeTopRightBetween, -0.7330383F, 1.867502F, 2.181662F);
      CollarSpikeTopLeftBetween = new ModelRenderer(this, 0, 0);
      CollarSpikeTopLeftBetween.addBox(0F, 0F, -0.5F, 0, 2, 1);
      CollarSpikeTopLeftBetween.setRotationPoint(0.8F, 15.2F, -4F);
      CollarSpikeTopLeftBetween.setTextureSize(64, 32);
      CollarSpikeTopLeftBetween.mirror = true;
      setRotation(CollarSpikeTopLeftBetween, -0.7330383F, -1.867502F, -2.181662F);
      SideLowerSpikeRight = new ModelRenderer(this, 51, 1);
      SideLowerSpikeRight.addBox(-0.5F, -0.5F, 0F, 1, 1, 5);
      SideLowerSpikeRight.setRotationPoint(-1.5F, 17.5F, 0F);
      SideLowerSpikeRight.setTextureSize(64, 32);
      SideLowerSpikeRight.mirror = true;
      setRotation(SideLowerSpikeRight, -0.2094395F, -0.3316126F, -0.0523599F);
      SideUpperSpikeRight = new ModelRenderer(this, 50, 0);
      SideUpperSpikeRight.addBox(-0.5F, -0.5F, 0F, 1, 1, 6);
      SideUpperSpikeRight.setRotationPoint(-1.5F, 17F, 0F);
      SideUpperSpikeRight.setTextureSize(64, 32);
      SideUpperSpikeRight.mirror = true;
      setRotation(SideUpperSpikeRight, -0.0174533F, -0.3490659F, -0.0174533F);
      RearSpikeRight = new ModelRenderer(this, 51, 1);
      RearSpikeRight.addBox(-0.5F, -0.5F, 0F, 1, 1, 5);
      RearSpikeRight.setRotationPoint(-1.4F, 17F, 0F);
      RearSpikeRight.setTextureSize(64, 32);
      RearSpikeRight.mirror = true;
      setRotation(RearSpikeRight, 0.2617994F, -0.3141593F, 0.1570796F);
      RearSpikeTopRight = new ModelRenderer(this, 51, 1);
      RearSpikeTopRight.addBox(-0.5F, -0.5F, 0F, 1, 1, 5);
      RearSpikeTopRight.setRotationPoint(-1.4F, 16.6F, 1F);
      RearSpikeTopRight.setTextureSize(64, 32);
      RearSpikeTopRight.mirror = true;
      setRotation(RearSpikeTopRight, 0.4712389F, 0.0349066F, -0.1745329F);
      RearSpikeTop = new ModelRenderer(this, 53, 3);
      RearSpikeTop.addBox(-0.5F, -0.5F, 0F, 1, 1, 3);
      RearSpikeTop.setRotationPoint(0F, 16.5F, 2F);
      RearSpikeTop.setTextureSize(64, 32);
      RearSpikeTop.mirror = true;
      setRotation(RearSpikeTop, 0.2443461F, 0F, 0F);
      SideLowerSpikeLeft = new ModelRenderer(this, 51, 1);
      SideLowerSpikeLeft.addBox(-0.5F, -0.5F, 0F, 1, 1, 5);
      SideLowerSpikeLeft.setRotationPoint(1.5F, 17.5F, 0F);
      SideLowerSpikeLeft.setTextureSize(64, 32);
      SideLowerSpikeLeft.mirror = true;
      setRotation(SideLowerSpikeLeft, -0.2094395F, 0.3316126F, 0.0523599F);
      SideUpperSpikeLeft = new ModelRenderer(this, 50, 0);
      SideUpperSpikeLeft.addBox(-0.5F, -0.5F, 0F, 1, 1, 6);
      SideUpperSpikeLeft.setRotationPoint(1.5F, 17F, 0F);
      SideUpperSpikeLeft.setTextureSize(64, 32);
      SideUpperSpikeLeft.mirror = true;
      setRotation(SideUpperSpikeLeft, -0.0174533F, 0.3490659F, 0.0174533F);
      RearSpikeLeft = new ModelRenderer(this, 51, 1);
      RearSpikeLeft.addBox(-0.5F, -0.5F, 0F, 1, 1, 5);
      RearSpikeLeft.setRotationPoint(1.4F, 17F, 0F);
      RearSpikeLeft.setTextureSize(64, 32);
      RearSpikeLeft.mirror = true;
      setRotation(RearSpikeLeft, 0.2617994F, 0.3141593F, -0.1570796F);
      RearSpikeTopLeft = new ModelRenderer(this, 51, 1);
      RearSpikeTopLeft.addBox(-0.5F, -0.5F, 0F, 1, 1, 5);
      RearSpikeTopLeft.setRotationPoint(1.4F, 16.6F, 1F);
      RearSpikeTopLeft.setTextureSize(64, 32);
      RearSpikeTopLeft.mirror = true;
      setRotation(RearSpikeTopLeft, 0.4712389F, -0.0349066F, 0.1745329F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    EarR.render(f5);
    EarL.render(f5);
    Head.render(f5);
    Muzzle.render(f5);
    Nose.render(f5);
    Jaw.render(f5);
    Chest.render(f5);
    LowerBody.render(f5);
    FrontUpperLegR.render(f5);
    FrontLowerLegR.render(f5);
    FrontPawR.render(f5);
    FrontUpperLegL.render(f5);
    FrontLowerLegL.render(f5);
    FrontPawL.render(f5);
    RearUpperLegR.render(f5);
    RearLegJointR.render(f5);
    RearLowerLegR.render(f5);
    RearPawR.render(f5);
    RearUpperLegL.render(f5);
    RearLegJointL.render(f5);
    RearLowerLegL.render(f5);
    RearPawL.render(f5);
    CollarSpikelow.render(f5);
    CollarSpikeRight.render(f5);
    CollarSpikeLeft.render(f5);
    CollarSpikeHigh.render(f5);
    CollarSpikeLowRight.render(f5);
    CollarSpikeLowLeft.render(f5);
    CollarSpikelowLeftBetween.render(f5);
    CollarSpikelowRightBetween.render(f5);
    CollarSpikeRightBetween.render(f5);
    CollarSpikeLeftBetween.render(f5);
    CollarSpikeTopRightBetween.render(f5);
    CollarSpikeTopLeftBetween.render(f5);
    SideLowerSpikeRight.render(f5);
    SideUpperSpikeRight.render(f5);
    RearSpikeRight.render(f5);
    RearSpikeTopRight.render(f5);
    RearSpikeTop.render(f5);
    SideLowerSpikeLeft.render(f5);
    SideUpperSpikeLeft.render(f5);
    RearSpikeLeft.render(f5);
    RearSpikeTopLeft.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
