package pixelmon.Pokemon;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelPidgeot extends ModelBase
{
  //fields
    ModelRenderer Mane_10;
    ModelRenderer Mane_9;
    ModelRenderer Mane_8;
    ModelRenderer Mane_7;
    ModelRenderer Mane_6;
    ModelRenderer Mane_5;
    ModelRenderer Mane_4;
    ModelRenderer Mane_3;
    ModelRenderer Mane_2;
    ModelRenderer Mane_1;
    ModelRenderer Pecker_bottom;
    ModelRenderer Pecker_end;
    ModelRenderer Pecker_Top;
    ModelRenderer Head_bottom;
    ModelRenderer Head_Top;
    ModelRenderer Body_Topmiddle;
    ModelRenderer Body_Top;
    ModelRenderer Body_LowerMiddle;
    ModelRenderer Body_bottom;
    ModelRenderer Back_top;
    ModelRenderer Back_middle;
    ModelRenderer Back_lower;
    ModelRenderer Butt_front;
    ModelRenderer Butt_bottom;
    ModelRenderer Butt_back;
    ModelRenderer Tail;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
    ModelRenderer Tail4;
    ModelRenderer Tail5;
    ModelRenderer Tail6;
    ModelRenderer Left_main;
    ModelRenderer Left_inner;
    ModelRenderer Right_inner;
    ModelRenderer Right_main;
    ModelRenderer Right_bottom;
    ModelRenderer Left_bottom;
    ModelRenderer Right_Thigh;
    ModelRenderer Left_thigh;
    ModelRenderer left_ankle;
    ModelRenderer Right_ankle;
    ModelRenderer Left_middletoe;
    ModelRenderer right_middletoe;
    ModelRenderer left_lefttoe;
    ModelRenderer right_righttoe;
    ModelRenderer right_lefttoe;
    ModelRenderer left_righttoe;
    ModelRenderer left_backtoe;
    ModelRenderer right_backtoe;
    ModelRenderer Middleleft_feather;
    ModelRenderer Middleright_feather;
    ModelRenderer Left_feather;
    ModelRenderer right_feather;
  
  public ModelPidgeot()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Mane_10 = new ModelRenderer(this, 94, 34);
      Mane_10.addBox(-1.5F, 0F, 0F, 3, 1, 2);
      Mane_10.setRotationPoint(0F, 0.6F, 3.2F);
      Mane_10.setTextureSize(128, 64);
      Mane_10.mirror = true;
      setRotation(Mane_10, -0.6981317F, 0F, 0F);
      Mane_9 = new ModelRenderer(this, 91, 37);
      Mane_9.addBox(-3F, 0F, 0F, 6, 1, 2);
      Mane_9.setRotationPoint(0F, 1F, 2F);
      Mane_9.setTextureSize(128, 64);
      Mane_9.mirror = true;
      setRotation(Mane_9, -0.2617994F, 0F, 0F);
      Mane_8 = new ModelRenderer(this, 93, 40);
      Mane_8.addBox(-2F, 0F, 0F, 4, 1, 2);
      Mane_8.setRotationPoint(0F, 0.1F, 1.3F);
      Mane_8.setTextureSize(128, 64);
      Mane_8.mirror = true;
      setRotation(Mane_8, -0.2617994F, 0F, 0F);
      Mane_7 = new ModelRenderer(this, 91, 43);
      Mane_7.addBox(-3.5F, 0F, 0F, 7, 1, 2);
      Mane_7.setRotationPoint(0F, 1F, 0F);
      Mane_7.setTextureSize(128, 64);
      Mane_7.mirror = true;
      setRotation(Mane_7, 0F, 0F, 0F);
      Mane_6 = new ModelRenderer(this, 92, 46);
      Mane_6.addBox(-2.5F, 0F, 0F, 5, 1, 2);
      Mane_6.setRotationPoint(0F, 0.2F, -0.8F);
      Mane_6.setTextureSize(128, 64);
      Mane_6.mirror = true;
      setRotation(Mane_6, 0.0872665F, 0F, 0F);
      Mane_5 = new ModelRenderer(this, 93, 49);
      Mane_5.addBox(-3.5F, 0F, 0F, 7, 1, 2);
      Mane_5.setRotationPoint(0F, 1.3F, -2F);
      Mane_5.setTextureSize(128, 64);
      Mane_5.mirror = true;
      setRotation(Mane_5, 0.1745329F, 0F, 0F);
      Mane_4 = new ModelRenderer(this, 95, 52);
      Mane_4.addBox(-2.5F, 0F, 0F, 5, 1, 2);
      Mane_4.setRotationPoint(0F, 0.9F, -2.7F);
      Mane_4.setTextureSize(128, 64);
      Mane_4.mirror = true;
      setRotation(Mane_4, 0.3490659F, 0F, 0F);
      Mane_3 = new ModelRenderer(this, 92, 55);
      Mane_3.addBox(-3F, 0F, 0F, 6, 1, 2);
      Mane_3.setRotationPoint(0F, 2.2F, -4F);
      Mane_3.setTextureSize(128, 64);
      Mane_3.mirror = true;
      setRotation(Mane_3, 0.4363323F, 0F, 0F);
      Mane_2 = new ModelRenderer(this, 94, 58);
      Mane_2.addBox(-2F, 0F, 0F, 4, 1, 2);
      Mane_2.setRotationPoint(0F, 2.2F, -4.2F);
      Mane_2.setTextureSize(128, 64);
      Mane_2.mirror = true;
      setRotation(Mane_2, 0.6981317F, 0F, 0F);
      Mane_1 = new ModelRenderer(this, 95, 61);
      Mane_1.addBox(-2F, -2F, 0F, 4, 2, 1);
      Mane_1.setRotationPoint(0F, 4F, -5F);
      Mane_1.setTextureSize(128, 64);
      Mane_1.mirror = true;
      setRotation(Mane_1, -0.4014257F, 0F, 0F);
      Pecker_bottom = new ModelRenderer(this, 58, 38);
      Pecker_bottom.addBox(-1F, 0F, 0F, 2, 1, 4);
      Pecker_bottom.setRotationPoint(0F, 5F, -7F);
      Pecker_bottom.setTextureSize(128, 64);
      Pecker_bottom.mirror = true;
      setRotation(Pecker_bottom, -0.2617994F, 0F, 0F);
      Pecker_end = new ModelRenderer(this, 58, 35);
      Pecker_end.addBox(-1.5F, 0F, 0F, 3, 2, 1);
      Pecker_end.setRotationPoint(0F, 4F, -7F);
      Pecker_end.setTextureSize(128, 64);
      Pecker_end.mirror = true;
      setRotation(Pecker_end, -0.2617994F, 0F, 0F);
      Pecker_Top = new ModelRenderer(this, 58, 29);
      Pecker_Top.addBox(-1.5F, 0F, 0F, 3, 2, 4);
      Pecker_Top.setRotationPoint(0F, 4F, -7F);
      Pecker_Top.setTextureSize(128, 64);
      Pecker_Top.mirror = true;
      setRotation(Pecker_Top, 0.0872665F, 0F, 0F);
      Pecker_Top.mirror = false;
      Head_bottom = new ModelRenderer(this, 36, 53);
      Head_bottom.addBox(-3F, 0F, 0F, 6, 3, 8);
      Head_bottom.setRotationPoint(0F, 3F, -4F);
      Head_bottom.setTextureSize(128, 64);
      Head_bottom.mirror = true;
      setRotation(Head_bottom, 0F, 0F, 0F);
      Head_Top = new ModelRenderer(this, 36, 45);
      Head_Top.addBox(-2.5F, 0F, 0F, 5, 1, 7);
      Head_Top.setRotationPoint(0F, 2F, -3F);
      Head_Top.setTextureSize(128, 64);
      Head_Top.mirror = true;
      setRotation(Head_Top, 0F, 0F, 0F);
      Body_Topmiddle = new ModelRenderer(this, 0, 49);
      Body_Topmiddle.addBox(-4F, 0F, 0F, 8, 5, 10);
      Body_Topmiddle.setRotationPoint(0F, 9F, -4F);
      Body_Topmiddle.setTextureSize(128, 64);
      Body_Topmiddle.mirror = true;
      setRotation(Body_Topmiddle, 0.1745329F, 0F, 0F);
      Body_Top = new ModelRenderer(this, 0, 37);
      Body_Top.addBox(-3.5F, 0F, 0F, 7, 3, 9);
      Body_Top.setRotationPoint(0F, 6F, -4F);
      Body_Top.setTextureSize(128, 64);
      Body_Top.mirror = true;
      setRotation(Body_Top, 0F, 0F, 0F);
      Body_LowerMiddle = new ModelRenderer(this, 0, 26);
      Body_LowerMiddle.addBox(-4F, 0F, 0F, 8, 2, 9);
      Body_LowerMiddle.setRotationPoint(0F, 14F, -3.1F);
      Body_LowerMiddle.setTextureSize(128, 64);
      Body_LowerMiddle.mirror = true;
      setRotation(Body_LowerMiddle, 0.5235988F, 0F, 0F);
      Body_bottom = new ModelRenderer(this, 0, 13);
      Body_bottom.addBox(-4F, -6F, 0F, 8, 6, 7);
      Body_bottom.setRotationPoint(0F, 15.7F, -2F);
      Body_bottom.setTextureSize(128, 64);
      Body_bottom.mirror = true;
      setRotation(Body_bottom, -0.5235988F, 0F, 0F);
      Body_bottom.mirror = false;
      Back_top = new ModelRenderer(this, 34, 36);
      Back_top.addBox(-3.5F, 0F, -5F, 7, 4, 5);
      Back_top.setRotationPoint(0F, 4F, 4F);
      Back_top.setTextureSize(128, 64);
      Back_top.mirror = true;
      setRotation(Back_top, 0.6806784F, 0F, 0F);
      Back_middle = new ModelRenderer(this, 34, 31);
      Back_middle.addBox(-3.5F, 0F, 0F, 7, 2, 3);
      Back_middle.setRotationPoint(0F, 7F, 6.4F);
      Back_middle.setTextureSize(128, 64);
      Back_middle.mirror = true;
      setRotation(Back_middle, -1.047198F, 0F, 0F);
      Back_lower = new ModelRenderer(this, 34, 22);
      Back_lower.addBox(-3.5F, 0F, 0F, 7, 4, 5);
      Back_lower.setRotationPoint(0F, 9.6F, 7.9F);
      Back_lower.setTextureSize(128, 64);
      Back_lower.mirror = true;
      setRotation(Back_lower, -1.22173F, 0F, 0F);
      Butt_front = new ModelRenderer(this, 30, 14);
      Butt_front.addBox(-4F, 0F, 0F, 8, 4, 4);
      Butt_front.setRotationPoint(0F, 11F, 6F);
      Butt_front.setTextureSize(128, 64);
      Butt_front.mirror = true;
      setRotation(Butt_front, -1.082104F, 0F, 0F);
      Butt_bottom = new ModelRenderer(this, 64, 53);
      Butt_bottom.addBox(-4F, -6F, 0F, 8, 6, 5);
      Butt_bottom.setRotationPoint(0F, 19.1F, 4F);
      Butt_bottom.setTextureSize(128, 64);
      Butt_bottom.mirror = true;
      setRotation(Butt_bottom, -0.0872665F, 0F, 0F);
      Butt_back = new ModelRenderer(this, 60, 43);
      Butt_back.addBox(-3.5F, -5F, 0F, 7, 5, 5);
      Butt_back.setRotationPoint(0F, 19.6F, 9F);
      Butt_back.setTextureSize(128, 64);
      Butt_back.mirror = true;
      setRotation(Butt_back, 0.7853982F, 0F, 0F);
      Tail = new ModelRenderer(this, 91, 31);
      Tail.addBox(-3F, 0F, 0F, 6, 1, 2);
      Tail.setRotationPoint(0F, 1.6F, 4F);
      Tail.setTextureSize(128, 64);
      Tail.mirror = true;
      setRotation(Tail, -0.5235988F, 0F, 0F);
      Tail1 = new ModelRenderer(this, 92, 28);
      Tail1.addBox(-2.5F, 0F, 0F, 5, 1, 2);
      Tail1.setRotationPoint(0F, 2.6F, 5.8F);
      Tail1.setTextureSize(128, 64);
      Tail1.mirror = true;
      setRotation(Tail1, -0.6981317F, 0F, 0F);
      Tail2 = new ModelRenderer(this, 92, 25);
      Tail2.addBox(-2.5F, 0F, 0F, 5, 1, 2);
      Tail2.setRotationPoint(0F, 3.9F, 7.3F);
      Tail2.setTextureSize(128, 64);
      Tail2.mirror = true;
      setRotation(Tail2, -0.7853982F, 0F, 0F);
      Tail3 = new ModelRenderer(this, 92, 22);
      Tail3.addBox(-2.5F, 0F, 0F, 5, 1, 2);
      Tail3.setRotationPoint(0F, 5.4F, 8.7F);
      Tail3.setTextureSize(128, 64);
      Tail3.mirror = true;
      setRotation(Tail3, -0.8726646F, 0F, 0F);
      Tail4 = new ModelRenderer(this, 93, 19);
      Tail4.addBox(-2F, 0F, 0F, 4, 1, 2);
      Tail4.setRotationPoint(0F, 7F, 10F);
      Tail4.setTextureSize(128, 64);
      Tail4.mirror = true;
      setRotation(Tail4, -1.047198F, 0F, 0F);
      Tail5 = new ModelRenderer(this, 93, 16);
      Tail5.addBox(-2F, -1.133333F, 0F, 4, 1, 2);
      Tail5.setRotationPoint(0F, 9.3F, 10.1F);
      Tail5.setTextureSize(128, 64);
      Tail5.mirror = true;
      setRotation(Tail5, -0.8726646F, 0F, 0F);
      Tail6 = new ModelRenderer(this, 94, 13);
      Tail6.addBox(-1.5F, -1F, 0F, 3, 1, 2);
      Tail6.setRotationPoint(0F, 10.7F, 11.5F);
      Tail6.setTextureSize(128, 64);
      Tail6.mirror = true;
      setRotation(Tail6, -0.6981317F, 0F, 0F);
      Left_main = new ModelRenderer(this, 79, 0);
      Left_main.addBox(0F, 0F, 0F, 1, 16, 6);
      Left_main.setRotationPoint(4F, 9F, 0F);
      Left_main.setTextureSize(128, 64);
      Left_main.mirror = true;
      setRotation(Left_main, 0.5235988F, 0F, 0F);
      Left_inner = new ModelRenderer(this, 47, 0);
      Left_inner.addBox(0F, 0F, 0F, 1, 6, 8);
      Left_inner.setRotationPoint(3F, 10F, -1.8F);
      Left_inner.setTextureSize(128, 64);
      Left_inner.mirror = true;
      setRotation(Left_inner, 0.5235988F, 0F, 0F);
      Right_inner = new ModelRenderer(this, 0, 0);
      Right_inner.addBox(0F, 0F, 0F, 1, 6, 8);
      Right_inner.setRotationPoint(-4F, 10F, -1.8F);
      Right_inner.setTextureSize(128, 64);
      Right_inner.mirror = true;
      setRotation(Right_inner, 0.5235988F, 0F, 0F);
      Right_main = new ModelRenderer(this, 65, 0);
      Right_main.addBox(0F, 0F, 0F, 1, 16, 6);
      Right_main.setRotationPoint(-5F, 9F, 0F);
      Right_main.setTextureSize(128, 64);
      Right_main.mirror = true;
      setRotation(Right_main, 0.5235988F, 0F, 0F);
      Right_bottom = new ModelRenderer(this, 41, 0);
      Right_bottom.addBox(0F, 0F, -2F, 1, 12, 2);
      Right_bottom.setRotationPoint(-5F, 9F, 0F);
      Right_bottom.setTextureSize(128, 64);
      Right_bottom.mirror = true;
      setRotation(Right_bottom, 0.5235988F, 0F, 0F);
      Left_bottom = new ModelRenderer(this, 35, 0);
      Left_bottom.addBox(0F, 0F, -2F, 1, 12, 2);
      Left_bottom.setRotationPoint(4F, 9F, 0F);
      Left_bottom.setTextureSize(128, 64);
      Left_bottom.mirror = true;
      setRotation(Left_bottom, 0.5235988F, 0F, 0F);
      Right_Thigh = new ModelRenderer(this, 23, 0);
      Right_Thigh.addBox(-3F, 0F, 0F, 3, 3, 3);
      Right_Thigh.setRotationPoint(-1F, 17F, 2F);
      Right_Thigh.setTextureSize(128, 64);
      Right_Thigh.mirror = true;
      setRotation(Right_Thigh, 0F, 0F, 0F);
      Left_thigh = new ModelRenderer(this, 23, 6);
      Left_thigh.addBox(0F, 0F, 0F, 3, 3, 3);
      Left_thigh.setRotationPoint(1F, 17F, 2F);
      Left_thigh.setTextureSize(128, 64);
      Left_thigh.mirror = true;
      setRotation(Left_thigh, 0F, 0F, 0F);
      left_ankle = new ModelRenderer(this, 93, 0);
      left_ankle.addBox(0F, 0F, 0F, 2, 3, 2);
      left_ankle.setRotationPoint(1.5F, 20F, 3F);
      left_ankle.setTextureSize(128, 64);
      left_ankle.mirror = true;
      setRotation(left_ankle, 0F, 0F, 0F);
      Right_ankle = new ModelRenderer(this, 93, 5);
      Right_ankle.addBox(-2F, 0F, 0F, 2, 3, 2);
      Right_ankle.setRotationPoint(-1.5F, 20F, 3F);
      Right_ankle.setTextureSize(128, 64);
      Right_ankle.mirror = true;
      setRotation(Right_ankle, 0F, 0F, 0F);
      Left_middletoe = new ModelRenderer(this, 83, 22);
      Left_middletoe.addBox(0F, 0F, -3F, 1, 1, 3);
      Left_middletoe.setRotationPoint(2F, 22F, 3F);
      Left_middletoe.setTextureSize(128, 64);
      Left_middletoe.mirror = true;
      setRotation(Left_middletoe, 0.0872665F, 0F, 0F);
      right_middletoe = new ModelRenderer(this, 83, 26);
      right_middletoe.addBox(-1F, 0F, -3F, 1, 1, 3);
      right_middletoe.setRotationPoint(-2F, 22F, 3F);
      right_middletoe.setTextureSize(128, 64);
      right_middletoe.mirror = true;
      setRotation(right_middletoe, 0.0872665F, 0F, 0F);
      left_lefttoe = new ModelRenderer(this, 83, 30);
      left_lefttoe.addBox(0F, 0F, -3F, 1, 1, 3);
      left_lefttoe.setRotationPoint(3F, 22F, 3F);
      left_lefttoe.setTextureSize(128, 64);
      left_lefttoe.mirror = true;
      setRotation(left_lefttoe, 0.0872665F, -0.3490659F, 0F);
      right_righttoe = new ModelRenderer(this, 83, 34);
      right_righttoe.addBox(-1F, 0F, -3F, 1, 1, 3);
      right_righttoe.setRotationPoint(-3F, 22F, 3F);
      right_righttoe.setTextureSize(128, 64);
      right_righttoe.mirror = true;
      setRotation(right_righttoe, 0.0872665F, 0.3490659F, 0F);
      right_lefttoe = new ModelRenderer(this, 83, 38);
      right_lefttoe.addBox(0F, 0F, -3F, 1, 1, 3);
      right_lefttoe.setRotationPoint(-2F, 22F, 3F);
      right_lefttoe.setTextureSize(128, 64);
      right_lefttoe.mirror = true;
      setRotation(right_lefttoe, 0.0872665F, -0.3490659F, 0F);
      left_righttoe = new ModelRenderer(this, 75, 22);
      left_righttoe.addBox(-1F, 0F, -3F, 1, 1, 3);
      left_righttoe.setRotationPoint(2F, 22F, 3F);
      left_righttoe.setTextureSize(128, 64);
      left_righttoe.mirror = true;
      setRotation(left_righttoe, 0.0872665F, 0.3490659F, 0F);
      left_backtoe = new ModelRenderer(this, 77, 26);
      left_backtoe.addBox(0F, 0F, 0F, 1, 1, 2);
      left_backtoe.setRotationPoint(2F, 22F, 5F);
      left_backtoe.setTextureSize(128, 64);
      left_backtoe.mirror = true;
      setRotation(left_backtoe, -0.0872665F, 0F, 0F);
      right_backtoe = new ModelRenderer(this, 78, 29);
      right_backtoe.addBox(-1F, 0F, 0F, 1, 1, 2);
      right_backtoe.setRotationPoint(-2F, 22F, 5F);
      right_backtoe.setTextureSize(128, 64);
      right_backtoe.mirror = true;
      setRotation(right_backtoe, -0.0872665F, 0F, 0F);
      Middleleft_feather = new ModelRenderer(this, 108, 0);
      Middleleft_feather.addBox(0F, 0F, 0F, 2, 1, 8);
      Middleleft_feather.setRotationPoint(0F, 16F, 12F);
      Middleleft_feather.setTextureSize(128, 64);
      Middleleft_feather.mirror = true;
      setRotation(Middleleft_feather, -0.2617994F, 0.0523599F, 0F);
      Middleright_feather = new ModelRenderer(this, 108, 9);
      Middleright_feather.addBox(-2F, 0F, 0F, 2, 1, 8);
      Middleright_feather.setRotationPoint(0F, 16F, 12F);
      Middleright_feather.setTextureSize(128, 64);
      Middleright_feather.mirror = true;
      setRotation(Middleright_feather, -0.2617994F, -0.0523599F, 0F);
      Left_feather = new ModelRenderer(this, 110, 18);
      Left_feather.addBox(0F, 0F, 0F, 2, 1, 7);
      Left_feather.setRotationPoint(1.5F, 16F, 12F);
      Left_feather.setTextureSize(128, 64);
      Left_feather.mirror = true;
      setRotation(Left_feather, -0.3490659F, 0.1745329F, 0F);
      right_feather = new ModelRenderer(this, 110, 26);
      right_feather.addBox(-2F, 0F, 0F, 2, 1, 7);
      right_feather.setRotationPoint(-1.53F, 16F, 12F);
      right_feather.setTextureSize(128, 64);
      right_feather.mirror = true;
      setRotation(right_feather, -0.3490659F, -0.1745329F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Mane_10.render(f5);
    Mane_9.render(f5);
    Mane_8.render(f5);
    Mane_7.render(f5);
    Mane_6.render(f5);
    Mane_5.render(f5);
    Mane_4.render(f5);
    Mane_3.render(f5);
    Mane_2.render(f5);
    Mane_1.render(f5);
    Pecker_bottom.render(f5);
    Pecker_end.render(f5);
    Pecker_Top.render(f5);
    Head_bottom.render(f5);
    Head_Top.render(f5);
    Body_Topmiddle.render(f5);
    Body_Top.render(f5);
    Body_LowerMiddle.render(f5);
    Body_bottom.render(f5);
    Back_top.render(f5);
    Back_middle.render(f5);
    Back_lower.render(f5);
    Butt_front.render(f5);
    Butt_bottom.render(f5);
    Butt_back.render(f5);
    Tail.render(f5);
    Tail1.render(f5);
    Tail2.render(f5);
    Tail3.render(f5);
    Tail4.render(f5);
    Tail5.render(f5);
    Tail6.render(f5);
    Left_main.render(f5);
    Left_inner.render(f5);
    Right_inner.render(f5);
    Right_main.render(f5);
    Right_bottom.render(f5);
    Left_bottom.render(f5);
    Right_Thigh.render(f5);
    Left_thigh.render(f5);
    left_ankle.render(f5);
    Right_ankle.render(f5);
    Left_middletoe.render(f5);
    right_middletoe.render(f5);
    left_lefttoe.render(f5);
    right_righttoe.render(f5);
    right_lefttoe.render(f5);
    left_righttoe.render(f5);
    left_backtoe.render(f5);
    right_backtoe.render(f5);
    Middleleft_feather.render(f5);
    Middleright_feather.render(f5);
    Left_feather.render(f5);
    right_feather.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
