// Date: 25/06/2012 11:06:13 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package pixelmon.Pokemon;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelEkans extends ModelBase {
	// fields
	ModelRenderer Body3;
	ModelRenderer HEADPIECE;
	ModelRenderer B1;
	ModelRenderer Head3;
	ModelRenderer Head2;
	ModelRenderer Head1;
	ModelRenderer BottomMouth;
	ModelRenderer Body1;
	ModelRenderer T1;
	ModelRenderer T2;
	ModelRenderer T3;
	ModelRenderer T4;
	ModelRenderer T5;
	ModelRenderer T6;
	ModelRenderer T7;
	ModelRenderer Tail1;
	ModelRenderer Tail2;
	ModelRenderer Tail3;
	ModelRenderer Tail4;
	ModelRenderer Tail5;
	ModelRenderer Tail6;
	ModelRenderer Tail7;
	ModelRenderer Tailtip;

	public ModelEkans() {
		textureWidth = 64;
		textureHeight = 128;
		setTextureOffset("HEADPIECE.HEADFOLDER", 0, 0);
		setTextureOffset("B1.Folder8", 0, 0);

		Body3 = new ModelRenderer(this, 40, 118);
		Body3.addBox(-2F, 0F, 0F, 4, 4, 6);
		Body3.setRotationPoint(0F, 18.2F, -17.9F);
		Body3.setTextureSize(64, 128);
		Body3.mirror = true;
		setRotation(Body3, -0.3316126F, 0F, 0F);
		HEADPIECE = new ModelRenderer(this, "HEADPIECE");
		HEADPIECE.setRotationPoint(0F, 0F, 0F);
		setRotation(HEADPIECE, 0F, 0F, 0F);
		HEADPIECE.mirror = true;
		Head3 = new ModelRenderer(this, 0, 79);
		Head3.addBox(-2.5F, 0F, -4F, 5, 3, 4);
		Head3.setRotationPoint(0F, 19F, -22F);
		Head3.setTextureSize(64, 128);
		Head3.mirror = true;
		setRotation(Head3, 0F, 0F, 0F);
		Head1 = new ModelRenderer(this, 0, 90);
		Head1.addBox(-2.5F, -2F, -4F, 5, 5, 4);
		Head1.setRotationPoint(0F, 19F, -18F);
		Head1.setTextureSize(64, 128);
		Head1.mirror = true;
		setRotation(Head1, 0F, 0F, 0F);
		Head2 = new ModelRenderer(this, 0, 110);
		Head2.addBox(-2F, 0F, -4F, 4, 3, 4);
		Head2.setRotationPoint(0F, 17.1F, -22F);
		Head2.setTextureSize(64, 128);
		Head2.mirror = true;
		setRotation(Head2, 0.4833219F, 0F, 0F);
		BottomMouth = new ModelRenderer(this, 1, 33);
		BottomMouth.addBox(0F, 0F, -6F, 5, 1, 8);
		BottomMouth.setRotationPoint(-2.5F, 21.4F, -19.5F);
		BottomMouth.setTextureSize(64, 128);
		BottomMouth.mirror = true;
		setRotation(BottomMouth, 0.2883408F, 0F, 0F);
		HEADPIECE.addChild(Head1);
		HEADPIECE.addChild(Head2);
		HEADPIECE.addChild(Head3);
		HEADPIECE.addChild(BottomMouth);
		B1 = new ModelRenderer(this, "B1");
		B1.setRotationPoint(0F, 0F, 0F);
		setRotation(B1, 0F, 0F, 0F);
		B1.mirror = true;
		Body1 = new ModelRenderer(this, 23, 117);
		Body1.addBox(-2F, 0F, -4F, 4, 7, 4);
		Body1.setRotationPoint(0F, 20F, -13.5F);
		Body1.setTextureSize(64, 128);
		Body1.mirror = true;
		setRotation(Body1, 1.570796F, 0F, 0F);
		B1.addChild(Body1);
		T7 = new ModelRenderer(this, "T7");
		T7.setRotationPoint(0F, 0F, 0F);
		setRotation(T7, 0F, 0F, 0F);
		T7.mirror = true;
		Tail7 = new ModelRenderer(this, 0, 62);
		Tail7.addBox(-2F, 0F, 0F, 4, 4, 8);
		Tail7.setRotationPoint(0F, 20F, -7.5F);
		Tail7.setTextureSize(64, 128);
		Tail7.mirror = true;
		setRotation(Tail7, 0F, 0F, 0F);
		T7.addChild(Tail7);
		T1 = new ModelRenderer(this, "T1");
		T1.setRotationPoint(0F, 20F, 0F);
		setRotation(T1, 0F, 0F, 0F);
		T1.mirror = true;
		Tail1 = new ModelRenderer(this, 0, 62);
		Tail1.addBox(-2F, 0F, 0F, 4, 4, 8);
		Tail1.setRotationPoint(0F, 0F, -0.5F);
		Tail1.setTextureSize(64, 128);
		Tail1.mirror = true;
		setRotation(Tail1, 0F, 0F, 0F);
		T1.addChild(Tail1);
		T7.addChild(T1);
		T2 = new ModelRenderer(this, "T2");
		T2.setRotationPoint(0F, 0F, 0F);
		setRotation(T2, 0F, 0F, 0F);
		T2.mirror = true;
		Tail2 = new ModelRenderer(this, 0, 62);
		Tail2.addBox(-2F, 0F, 0F, 4, 4, 8);
		Tail2.setRotationPoint(0F, 0F, 6.5F);
		Tail2.setTextureSize(64, 128);
		Tail2.mirror = true;
		setRotation(Tail2, 0F, 0F, 0F);
		T2.addChild(Tail2);
		T1.addChild(T2);
		T3 = new ModelRenderer(this, "T3");
		T3.setRotationPoint(0F, 0F, 0F);
		setRotation(T3, 0F, 0F, 0F);
		T3.mirror = true;
		Tail3 = new ModelRenderer(this, 0, 62);
		Tail3.addBox(-2F, 0F, 0F, 4, 4, 8);
		Tail3.setRotationPoint(0F, 0F, 13.5F);
		Tail3.setTextureSize(64, 128);
		Tail3.mirror = true;
		setRotation(Tail3, 0F, 0F, 0F);
		T3.addChild(Tail3);
		T2.addChild(T3);
		T4 = new ModelRenderer(this, "T4");
		T4.setRotationPoint(0F, 0F, 0F);
		setRotation(T4, 0F, 0F, 0F);
		T4.mirror = true;
		Tail4 = new ModelRenderer(this, 0, 42);
		Tail4.addBox(-1.5F, 0F, 0F, 3, 3, 4);
		Tail4.setRotationPoint(0F, 0.5F, 20.5F);
		Tail4.setTextureSize(64, 128);
		Tail4.mirror = true;
		setRotation(Tail4, 0F, 0F, 0F);
		T4.addChild(Tail4);
		T3.addChild(T4);
		T5 = new ModelRenderer(this, "T5");
		T5.setRotationPoint(0F, 0F, 0F);
		setRotation(T5, 0F, 0F, 0F);
		T5.mirror = true;
		Tail5 = new ModelRenderer(this, 0, 14);
		Tail5.addBox(-1F, 0F, 0F, 2, 2, 3);
		Tail5.setRotationPoint(0F, 1F, 23.5F);
		Tail5.setTextureSize(64, 128);
		Tail5.mirror = true;
		setRotation(Tail5, 0F, 0F, 0F);
		T5.addChild(Tail5);
		T4.addChild(T5);
		T6 = new ModelRenderer(this, "T6");
		T6.setRotationPoint(0F, 0F, 0F);
		setRotation(T6, 0F, 0F, 0F);
		T6.mirror = true;
		Tail6 = new ModelRenderer(this, 0, 0);
		Tail6.addBox(-0.5F, 0F, 0F, 1, 1, 2);
		Tail6.setRotationPoint(0F, 1.5F, 25.5F);
		Tail6.setTextureSize(64, 128);
		Tail6.mirror = true;
		setRotation(Tail6, 0F, 0F, 0F);

		Tailtip = new ModelRenderer(this, 0, 14);
		Tailtip.addBox(0F, 0F, 0F, 1, 1, 1);
		Tailtip.setRotationPoint(-0.5F, 1.6F, 28.79F);
		Tailtip.setTextureSize(64, 128);
		Tailtip.mirror = true;
		setRotation(Tailtip, -0.0743572F, 0F, 0F);
		T6.addChild(Tail6);
		T6.addChild(Tailtip);
		T5.addChild(T6);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5);
		Body3.render(f5);
		HEADPIECE.render(f5);
		B1.render(f5);
		T7.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}
