// Date: 4/22/2012 8:51:43 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package pixelmon.Pokemon;

import net.minecraft.src.*;

public class ModelIvysaur extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer belly;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer bulb1;
    ModelRenderer bulb2;
    ModelRenderer leaf1;
    ModelRenderer leaf2;
    ModelRenderer leaf3;
    ModelRenderer leaf4;
    ModelRenderer leaf1a;
    ModelRenderer leaf2a;
    ModelRenderer leaf3a;
    ModelRenderer leaf4a;
  
  public ModelIvysaur()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 0, 28);
      head.addBox(-4F, -4F, -7F, 8, 7, 7);
      head.setRotationPoint(0F, 14F, -4F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 0, 42);
      body.addBox(-5F, 0F, -7F, 10, 14, 7);
      body.setRotationPoint(0F, 13F, -6F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 1.570796F, 0F, 0F);
      belly = new ModelRenderer(this, 30, 31);
      belly.addBox(-4F, -5F, -1F, 8, 10, 1);
      belly.setRotationPoint(0F, 20F, 0F);
      belly.setTextureSize(64, 64);
      belly.mirror = true;
      setRotation(belly, 1.570796F, 0F, 0F);
      leg1 = new ModelRenderer(this, 48, 54);
      leg1.addBox(-2F, 0F, -2F, 3, 6, 4);
      leg1.setRotationPoint(-5F, 18F, 7F);
      leg1.setTextureSize(64, 64);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 48, 44);
      leg2.addBox(-2F, 0F, -2F, 3, 6, 4);
      leg2.setRotationPoint(6F, 18F, 7F);
      leg2.setTextureSize(64, 64);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 48, 34);
      leg3.addBox(-2F, 0F, -2F, 3, 6, 4);
      leg3.setRotationPoint(-5F, 18F, -5F);
      leg3.setTextureSize(64, 64);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 48, 24);
      leg4.addBox(-2F, 0F, -2F, 3, 6, 4);
      leg4.setRotationPoint(6F, 18F, -5F);
      leg4.setTextureSize(64, 64);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      bulb1 = new ModelRenderer(this, 32, 0);
      bulb1.addBox(-4F, -4F, -4F, 8, 4, 8);
      bulb1.setRotationPoint(0F, 13F, 2F);
      bulb1.setTextureSize(64, 64);
      bulb1.mirror = true;
      setRotation(bulb1, 0F, 0F, 0F);
      bulb2 = new ModelRenderer(this, 48, 13);
      bulb2.addBox(-2F, -3F, -2F, 4, 3, 4);
      bulb2.setRotationPoint(0F, 9F, 2F);
      bulb2.setTextureSize(64, 64);
      bulb2.mirror = true;
      setRotation(bulb2, 0F, 0F, 0F);
      leaf1 = new ModelRenderer(this, 0, 0);
      leaf1.addBox(-6F, 0F, -3.5F, 6, 0, 7);
      leaf1.setRotationPoint(-4F, 13F, 2F);
      leaf1.setTextureSize(64, 64);
      leaf1.mirror = true;
      setRotation(leaf1, 0F, 0F, 0.6108652F);
      leaf2 = new ModelRenderer(this, 0, 7);
      leaf2.addBox(-6F, 0F, -3.5F, 6, 0, 7);
      leaf2.setRotationPoint(0F, 13F, 6F);
      leaf2.setTextureSize(64, 64);
      leaf2.mirror = true;
      setRotation(leaf2, 0F, 1.570796F, 0.6108652F);
      leaf3 = new ModelRenderer(this, 0, 14);
      leaf3.addBox(-6F, 0F, -3.5F, 6, 0, 7);
      leaf3.setRotationPoint(4F, 13F, 2F);
      leaf3.setTextureSize(64, 64);
      leaf3.mirror = true;
      setRotation(leaf3, 0F, 3.141593F, 0.6108652F);
      leaf4 = new ModelRenderer(this, 0, 21);
      leaf4.addBox(-6F, 0F, -3.5F, 6, 0, 7);
      leaf4.setRotationPoint(0F, 13F, -2F);
      leaf4.setTextureSize(64, 64);
      leaf4.mirror = true;
      setRotation(leaf4, 0F, -1.570796F, 1.308997F);
      leaf1a = new ModelRenderer(this, 17, 0);
      leaf1a.addBox(-4F, 0F, -2.5F, 4, 0, 5);
      leaf1a.setRotationPoint(-8.9F, 9.6F, 2F);
      leaf1a.setTextureSize(64, 64);
      leaf1a.mirror = true;
      setRotation(leaf1a, 0F, 0F, -0.7330383F);
      leaf2a = new ModelRenderer(this, 17, 6);
      leaf2a.addBox(-4F, 0F, -2.5F, 4, 0, 5);
      leaf2a.setRotationPoint(8.9F, 9.6F, 2F);
      leaf2a.setTextureSize(64, 64);
      leaf2a.mirror = true;
      setRotation(leaf2a, 0F, 3.141593F, -0.4537856F);
      leaf3a = new ModelRenderer(this, 17, 12);
      leaf3a.addBox(-4F, 0F, -2.5F, 4, 0, 5);
      leaf3a.setRotationPoint(0F, 9.6F, 10.9F);
      leaf3a.setTextureSize(64, 64);
      leaf3a.mirror = true;
      setRotation(leaf3a, 0F, 1.570796F, -0.8203047F);
      leaf4a = new ModelRenderer(this, 17, 18);
      leaf4a.addBox(-4F, 0F, -2.5F, 4, 0, 5);
      leaf4a.setRotationPoint(0F, 7.3F, -3.6F);
      leaf4a.setTextureSize(64, 64);
      leaf4a.mirror = true;
      setRotation(leaf4a, 0F, -1.570796F, -0.4537856F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    body.render(f5);
    belly.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    leg3.render(f5);
    leg4.render(f5);
    bulb1.render(f5);
    bulb2.render(f5);
    leaf1.render(f5);
    leaf2.render(f5);
    leaf3.render(f5);
    leaf4.render(f5);
    leaf1a.render(f5);
    leaf2a.render(f5);
    leaf3a.render(f5);
    leaf4a.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
