// Date: 11/07/2012 9:44:56 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package pixelmon.Pokemon;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelDratini extends ModelBase
{
  //fields
	ModelRenderer HEADPIECE;
    ModelRenderer Head_dot;
    ModelRenderer ear2;
    ModelRenderer ear1;
    ModelRenderer Eye2;
    ModelRenderer Eye1;
    ModelRenderer head3;
    ModelRenderer Head2;
    ModelRenderer Head1;
    ModelRenderer TAIL1PIECE;
    ModelRenderer TAIL2PIECE;
    ModelRenderer TAIL3PIECE;
    ModelRenderer TAIL4PIECE;
    ModelRenderer TAIL5PIECE;
    ModelRenderer TAIL6PIECE;
    ModelRenderer TAIL7PIECE;
    ModelRenderer TAIL8PIECE;
    ModelRenderer Tailcomponent;
    ModelRenderer tail2component;
    ModelRenderer tail3component;
    ModelRenderer tail4component;
    ModelRenderer tail5component;
    ModelRenderer tail6component;
    ModelRenderer tail6extra;
    ModelRenderer tail7extra;
    ModelRenderer racingstripe6;
    ModelRenderer racingstripe7;
    ModelRenderer tail7component1;
    ModelRenderer tail7component2;
    ModelRenderer tail9component;
    ModelRenderer racingstripe1;
    ModelRenderer racingstripe2;
    ModelRenderer racingstripe3;
    ModelRenderer racingstripe4;
    ModelRenderer racingstripe5;
    ModelRenderer tailtip;
    ModelRenderer Head;
    ModelRenderer EAR1PIECE;
    ModelRenderer EAR2PIECE;
  
    
  
  public ModelDratini()
  {
    textureWidth = 64;
    textureHeight = 32;
    
    
    
    
    
    
    
    
    
    HEADPIECE = new ModelRenderer(this, "HEADPIECE");
    HEADPIECE.setRotationPoint(0F, 20.6F, -18F);
    setRotation(HEADPIECE, 0F, 0F, 0F);
    HEADPIECE.mirror = true;
    
    
      Head_dot = new ModelRenderer(this, 0, 26);
      Head_dot.addBox(-0.5F, -1F, -4.3F, 1, 1, 1);
      Head_dot.setRotationPoint(0F, 0F, 0F);
      Head_dot.setTextureSize(64, 32);
      Head_dot.mirror = true;
      setRotation(Head_dot, -0.14835299F, 0F, 0F);
      
      ear2 = new ModelRenderer(this, 0, 18);
      ear2.addBox(-3F, -3F, -2F, 2, 3, 0);
      ear2.setRotationPoint(0F,0F,0F);
      ear2.setTextureSize(64, 32);
      ear2.mirror = true;
      setRotation(ear2, 0F, 0.4363323F, 0F);
      
      ear1 = new ModelRenderer(this, 0, 18);
      ear1.addBox(1F, -3F, -2F, 2, 3, 0);
      ear1.setRotationPoint(0F, 0F, 0F);
      ear1.setTextureSize(64, 32);
      ear1.mirror = true;
      setRotation(ear1, 0F, -0.4363323F, 0F);
      
      Eye2 = new ModelRenderer(this, 0, 6);
      Eye2.addBox(0F, 0F, 0F, 1, 2, 1);
      Eye2.setRotationPoint(-1.5F, -1F, -4.01F);
      Eye2.setTextureSize(64, 32);
      Eye2.mirror = true;
      setRotation(Eye2, 0F, 0F, 0F);
      
      Eye1 = new ModelRenderer(this, 0, 6);
      Eye1.addBox(0F, 0F, 0F, 1, 2, 1);
      Eye1.setRotationPoint(0.5F, -1F, -4.01F);
      Eye1.setTextureSize(64, 32);
      Eye1.mirror = true;
      setRotation(Eye1, 0F, 0F, 0F);
      
      head3 = new ModelRenderer(this, 0, 22);
      head3.addBox(0F, 0F, 0F, 2, 1, 1);
      head3.setRotationPoint(-1F, 1.3F, -4.7F);
      head3.setTextureSize(64, 32);
      head3.mirror = true;
      setRotation(head3, 0F, 0F, 0F);
      
      Head2 = new ModelRenderer(this, 0, 22);
      Head2.addBox(0F, 0F, 0F, 2, 1, 1);
      Head2.setRotationPoint(-1F, 0.8F, -4.7F);
      Head2.setTextureSize(64, 32);
      Head2.mirror = true;
      setRotation(Head2, 0F, 0F, 0F);
      
      Head1 = new ModelRenderer(this, 0, 10);
      Head1.addBox(-2F, -1.5F, -4F, 4, 4, 3);
      Head1.setRotationPoint(0F, 0F, 0F);
      Head1.setTextureSize(64, 32);
      Head1.mirror = true;
      setRotation(Head1, 0F, 0F, 0F);
     
      
    TAIL1PIECE = new ModelRenderer(this, "TAIL1PIECE");
    TAIL1PIECE.setRotationPoint(0F, 1F, 2F);
    setRotation(TAIL1PIECE, 0F, 0F, 0F);
    TAIL1PIECE.mirror = true;
    
    
      racingstripe1 = new ModelRenderer(this, 37, 10);
      racingstripe1.addBox(-1F, 0.8F,-3F, 2, 1, 3);
      racingstripe1.setRotationPoint(0F, 0F, 0F);
      racingstripe1.setTextureSize(64, 32);
      racingstripe1.mirror = true;
      setRotation(racingstripe1, -0.0743572F, 0F, 0F);
      
      Tailcomponent = new ModelRenderer(this, 15, 10);
      Tailcomponent.addBox(-1.5F, -1.3F, -3.1F, 3, 3, 3);
      Tailcomponent.setRotationPoint(0F,0F,0F);
      Tailcomponent.setTextureSize(64, 32);
      Tailcomponent.mirror = true;
      setRotation(Tailcomponent, -0.0743572F, 0F, 0F);
      
      
    TAIL2PIECE = new ModelRenderer(this, "TAIL2PIECE");
    TAIL2PIECE.setRotationPoint(0F, 1F, 4F);
    setRotation(TAIL2PIECE, 0F, 0F, 0F);
    TAIL2PIECE.mirror = true;
    
    
      tail2component = new ModelRenderer(this, 0, 0);
      tail2component.addBox(-1.5F, -1.5F, -4.5F, 3, 3, 4);
      tail2component.setRotationPoint(0F, 0F, 0F);
      tail2component.setTextureSize(64, 32);
      tail2component.mirror = true;
      setRotation(tail2component, -0.1858931F, 0F, 0F);
      
      racingstripe2 = new ModelRenderer(this, 34, 0);
      racingstripe2.addBox(-1F, 0.6F, -4.5F, 2, 1, 4);
      racingstripe2.setRotationPoint(0F, 0F, 0F);
      racingstripe2.setTextureSize(64, 32);
      racingstripe2.mirror = true;
      setRotation(racingstripe2, -0.1858931F, 0F, 0F);
      
    TAIL3PIECE = new ModelRenderer(this, "TAIL3PIECE");
    TAIL3PIECE.setRotationPoint(0F, 0.5F, 3F);
    setRotation(TAIL3PIECE, 0F, 0F, 0F);
    TAIL3PIECE.mirror = true;
    
      tail3component = new ModelRenderer(this, 0, 0);
      tail3component.addBox(0F, 0F, 0F, 3, 3, 4);
      tail3component.setRotationPoint(-1.5F, -2.1F, -3.9F);
      tail3component.setTextureSize(64, 32);
      tail3component.mirror = true;
      setRotation(tail3component, 0F, 0F, 0F);
      
      racingstripe3 = new ModelRenderer(this, 37, 0);
      racingstripe3.addBox(-1F, 0F, -4F, 2, 1, 4);
      racingstripe3.setRotationPoint(0F, 0F, 0F);
      racingstripe3.setTextureSize(64, 32);
      racingstripe3.mirror = true;
      setRotation(racingstripe3, 0F, 0F, 0F);
      
      
    TAIL4PIECE = new ModelRenderer(this, "TAIL4PIECE");
    TAIL4PIECE.setRotationPoint(-1.5F, -2.1F, 0F);
    setRotation(TAIL4PIECE, 0F, 0F, 0F);
    TAIL4PIECE.mirror = true;
    
    
      racingstripe4 = new ModelRenderer(this, 37, 0);
      racingstripe4.addBox(0.5F, 2.1F, 0F, 2, 1, 4);
      racingstripe4.setRotationPoint(0F, 0F, 0F);
      racingstripe4.setTextureSize(64, 32);
      racingstripe4.mirror = true;
      setRotation(racingstripe4, 0F, 0F, 0F);
      
      tail4component = new ModelRenderer(this, 0, 0);
      tail4component.addBox(0F, 0F, 0F, 3, 3, 4);
      tail4component.setRotationPoint(0F, 0F, 0F);
      tail4component.setTextureSize(64, 32);
      tail4component.mirror = true;
      setRotation(tail4component, 0F, 0F, 0F);
      
      
    TAIL5PIECE = new ModelRenderer(this, "TAIL5PIECE");
    TAIL5PIECE.setRotationPoint(0F, 1.5F, 8F);
    setRotation(TAIL5PIECE, 0F, 0F, 0F);
    TAIL5PIECE.mirror = true;
    
    
      tail5component = new ModelRenderer(this, 0, 0);
      tail5component.addBox(0F, -1.5F, -4F, 3, 3, 4);
      tail5component.setRotationPoint(0F, 0F, 0F);
      tail5component.setTextureSize(64, 32);
      tail5component.mirror = true;
      setRotation(tail5component, 0F, 0F, 0F);
      
      racingstripe5 = new ModelRenderer(this, 11, 24);
      racingstripe5.addBox(0.5F, 0.6F, -4F, 2, 1, 4);
      racingstripe5.setRotationPoint(0F, 0F, 0F);
      racingstripe5.setTextureSize(64, 32);
      racingstripe5.mirror = true;
      setRotation(racingstripe5, 0F, 0F, 0F);
      
      
    TAIL6PIECE = new ModelRenderer(this, "TAIL6PIECE");
    TAIL6PIECE.setRotationPoint(1.5F, 0F, 3F);
    setRotation(TAIL6PIECE, 0F, 0F, 0F);
    TAIL6PIECE.mirror = true;
    
    
      tail6extra = new ModelRenderer(this, 19, 0);
      tail6extra.addBox(-1F, -1F, -3.5F, 2, 1, 5);
      tail6extra.setRotationPoint(0F, 0F, 0F);
      tail6extra.setTextureSize(64, 32);
      tail6extra.mirror = true;
      setRotation(tail6extra, -0.1358052F, 0F, 0F);
      
      tail6component = new ModelRenderer(this, 19, 0);
      tail6component.addBox(0F, 0F, 0F, 2, 2, 5);
      tail6component.setRotationPoint(-1F, -0.5F, -3F);
      tail6component.setTextureSize(64, 32);
      tail6component.mirror = true;
      setRotation(tail6component, 0F, 0F, 0F);
      
      racingstripe6 = new ModelRenderer(this, 42, 0);
      racingstripe6.addBox(0F, 0F, 0F, 1, 2, 5);
      racingstripe6.setRotationPoint(-0.5F, -0.4F, -3F);
      racingstripe6.setTextureSize(64, 32);
      racingstripe6.mirror = true;
      setRotation(racingstripe6, 0F, 0F, 0F);
      
      
    TAIL7PIECE = new ModelRenderer(this, "TAIL7PIECE");
    TAIL7PIECE.setRotationPoint(0F, 0F, 2F);
    setRotation(TAIL7PIECE, 0F, 0F, 0F);
    TAIL7PIECE.mirror = true;
    
    
      tail7extra = new ModelRenderer(this, 19, 0);
      tail7extra.addBox(-1F, -0.7F, -1F, 2, 1, 5);
      tail7extra.setRotationPoint(0F, 0F, 0F);
      tail7extra.setTextureSize(64, 32);
      tail7extra.mirror = true;
      setRotation(tail7extra, -0.1858931F, 0F, 0F);
      
      tail7component1 = new ModelRenderer(this, 19, 0);
      tail7component1.addBox(0F, 0F, 0F, 2, 1, 3);
      tail7component1.setRotationPoint(-1F, 0.5F, 0F);
      tail7component1.setTextureSize(64, 32);
      tail7component1.mirror = true;
      setRotation(tail7component1, 0F, 0F, 0F);
      
      tail7component2 = new ModelRenderer(this, 19, 0);
      tail7component2.addBox(0F, 0F, 0F, 2, 1, 3);
      tail7component2.setRotationPoint(-1F, 0.1F, 0F);
      tail7component2.setTextureSize(64, 32);
      tail7component2.mirror = true;
      setRotation(tail7component2, 0F, 0F, 0F);
      
      racingstripe7 = new ModelRenderer(this, 36, 0);
      racingstripe7.addBox(0F, 0F, 0F, 1, 1, 3);
      racingstripe7.setRotationPoint(-0.5F, 0.6F, 0F);
      racingstripe7.setTextureSize(64, 32);
      racingstripe7.mirror = true;
      setRotation(racingstripe7, 0F, 0F, 0F);
      
      
    TAIL8PIECE = new ModelRenderer(this, "TAIL8COMPONENT");
    TAIL8PIECE.setRotationPoint(0F, 0.1F, 1F);
    setRotation(TAIL8PIECE, 0F, 0F, 0F);
    TAIL8PIECE.mirror = true;
    
    
      tailtip = new ModelRenderer(this, 22, 0);
      tailtip.addBox(0F, 0F, 0F, 2, 2, 3);
      tailtip.setRotationPoint(-1F, -0.6F, 0F);
      tailtip.setTextureSize(64, 32);
      tailtip.mirror = true;
      setRotation(tailtip, 0F, 0F, 0F);
      
      HEADPIECE.addChild(ear1);
      HEADPIECE.addChild(ear2);
      HEADPIECE.addChild(Head_dot);
      HEADPIECE.addChild(Eye1);
      HEADPIECE.addChild(Eye2);
      HEADPIECE.addChild(Head1);
      HEADPIECE.addChild(Head2);
      HEADPIECE.addChild(head3);
      HEADPIECE.addChild(TAIL1PIECE);
      
      TAIL1PIECE.addChild(racingstripe1);
      TAIL1PIECE.addChild(Tailcomponent);
      TAIL1PIECE.addChild(TAIL2PIECE);
      
      TAIL2PIECE.addChild(tail2component);
      TAIL2PIECE.addChild(racingstripe2);
      TAIL2PIECE.addChild(TAIL3PIECE);
      
      TAIL3PIECE.addChild(tail3component);
      TAIL3PIECE.addChild(racingstripe3);
      TAIL3PIECE.addChild(TAIL4PIECE);
      
      TAIL4PIECE.addChild(racingstripe4);
      TAIL4PIECE.addChild(tail4component);
      TAIL4PIECE.addChild(TAIL5PIECE);
      
      TAIL5PIECE.addChild(tail5component);
      TAIL5PIECE.addChild(racingstripe5);
      TAIL5PIECE.addChild(tail5component);
      TAIL5PIECE.addChild(TAIL6PIECE);
      
      TAIL6PIECE.addChild(tail6extra);
      TAIL6PIECE.addChild(tail6component);
      TAIL6PIECE.addChild(racingstripe6);
      TAIL6PIECE.addChild(TAIL7PIECE);
      
      TAIL7PIECE.addChild(tail7extra);
      TAIL7PIECE.addChild(tail7component1);
      TAIL7PIECE.addChild(racingstripe7);
      TAIL7PIECE.addChild(tail7component2);
      TAIL7PIECE.addChild(TAIL8PIECE);
      
      TAIL8PIECE.addChild(tailtip);
      
      
      
    
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    HEADPIECE.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
