package pixelmon.Pokemon;

import net.minecraft.src.Entity;
import net.minecraft.src.MathHelper;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelKrokorok extends ModelBase
{
  //fields
    ModelRenderer Right_cheek;
    ModelRenderer Right_eye;
    ModelRenderer Left_eye;
    ModelRenderer Mask_piece;
    ModelRenderer Left_cheek;
    ModelRenderer Bottom_cheek;
    ModelRenderer Back_of_head;
    ModelRenderer Back_of_right_eye;
    ModelRenderer Back_of_left_eye;
    ModelRenderer Lowerjaw_Right;
    ModelRenderer Upperjaw_Right;
    ModelRenderer Upperjaw_Left;
    ModelRenderer Lowerjaw_Left;
    ModelRenderer Muzzletip_Right;
    ModelRenderer Muzzletip_Left;
    ModelRenderer Segment1_Left;
    ModelRenderer Segment1_Right;
    ModelRenderer Segment2_Left;
    ModelRenderer Segment2_Right;
    ModelRenderer Middlemuzzle_Right;
    ModelRenderer Middlemuzzle_Left;
    ModelRenderer Topmuzzle_Right;
    ModelRenderer Topmuzzle_Left;
    ModelRenderer Fronttooth_Left;
    ModelRenderer Fronttooth_Right;
    ModelRenderer Left_Hip;
    ModelRenderer Left_Lower_leg;
    ModelRenderer Left_Upper_leg;
    ModelRenderer Left_Foot;
    ModelRenderer Le_Curve;
    ModelRenderer Left_Front_bump_1;
    ModelRenderer Left_Front_bump_2;
    ModelRenderer Left_Top_bump_1;
    ModelRenderer Left_Top_bump_2;
    ModelRenderer Left_Back_bump_1;
    ModelRenderer Left_Back_bump_2;
    ModelRenderer Right_Hip;
    ModelRenderer Right_Foot;
    ModelRenderer Right_Curve;
    ModelRenderer Right_Lower_leg;
    ModelRenderer Right_Upper_leg;
    ModelRenderer Right_Top_bump_1;
    ModelRenderer Right_Top_bump_2;
    ModelRenderer Right_Front_bump_1;
    ModelRenderer Right_Front_bump_2;
    ModelRenderer Right_Back_bump_1;
    ModelRenderer Right_Back_bump_2;
    ModelRenderer Right_Upperarm;
    ModelRenderer Right_Lowerarm;
    ModelRenderer Frontright_shoulder;
    ModelRenderer Backright_shoulder;
    ModelRenderer Sideright_shoulder;
    ModelRenderer Left_Upperarm;
    ModelRenderer Frontleft_shoulder;
    ModelRenderer Left_Lowerarm;
    ModelRenderer Backleft_shoulder;
    ModelRenderer Sideleft_shoulder;
    ModelRenderer Tailcurve1_Left;
    ModelRenderer Tailcurve1_Right;
    ModelRenderer Tailbase1_Left_Spine;
    ModelRenderer Tailbase1_Right_Spine;
    ModelRenderer Segment1_Right_T;
    ModelRenderer Segment1_Left_T;
    ModelRenderer Segment2_RightBottom;
    ModelRenderer Segment2_LeftTop;
    ModelRenderer Segment2_LeftBottom;
    ModelRenderer Segment2_RightTop;
    ModelRenderer Segment3_RightTop;
    ModelRenderer Segment3_RightBottom;
    ModelRenderer Tailbase3_Left_Spine;
    ModelRenderer Tailbase3_Right_Spine;
    ModelRenderer Segment4_Right;
    ModelRenderer Segment4_Left;
    ModelRenderer Segment5_Right;
    ModelRenderer Segment5_Left;
    ModelRenderer Tailbase5_Right_Spine;
    ModelRenderer Tailbase5_Left_Spine;
    ModelRenderer Segment6_Right;
    ModelRenderer Segment6_Left;
    ModelRenderer Segment7_Right;
    ModelRenderer Segment7_Left;
    ModelRenderer Tailbase7_Left_Spine;
    ModelRenderer Tailbase7_Right_Spine;
    ModelRenderer Segment8_Right;
    ModelRenderer Main;
    ModelRenderer Neck;
    ModelRenderer Belly;
    ModelRenderer Back_Right_Spine;
    ModelRenderer Back_Left_Spine;
    ModelRenderer Neck_Left_Spine;
    ModelRenderer Neck_Right_Spine;
    ModelRenderer Left_Arm;
    ModelRenderer Right_Arm;
    ModelRenderer Head;
    ModelRenderer Left_Leg;
    ModelRenderer Tail;
    ModelRenderer Right_Leg;
    ModelRenderer Body;
  
  public ModelKrokorok()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Right_cheek = new ModelRenderer(this, 0, 16);
      Right_cheek.addBox(-2.3F, -1.3F, -1F, 4, 2, 2);
      Right_cheek.setRotationPoint(0F, 11F, 0F);
      Right_cheek.setTextureSize(64, 32);
      Right_cheek.mirror = true;
      setRotation(Right_cheek, 0F, 0F, 0F);
      Right_eye = new ModelRenderer(this, 5, 11);
      Right_eye.addBox(-2.2F, -4.3F, -1F, 2, 2, 2);
      Right_eye.setRotationPoint(0F, 12F, 0F);
      Right_eye.setTextureSize(64, 32);
      Right_eye.mirror = true;
      setRotation(Right_eye, 0F, 0F, 0F);
      Left_eye = new ModelRenderer(this, 5, 11);
      Left_eye.addBox(0.2F, -4.3F, -1F, 2, 2, 2);
      Left_eye.setRotationPoint(0F, 12F, 0F);
      Left_eye.setTextureSize(64, 32);
      Left_eye.mirror = true;
      setRotation(Left_eye, 0F, 0F, 0F);
      Left_eye.mirror = false;
      Mask_piece = new ModelRenderer(this, 14, 13);
      Mask_piece.addBox(-0.5F, -3.4F, -1.1F, 1, 2, 0);
      Mask_piece.setRotationPoint(0F, 12F, 0F);
      Mask_piece.setTextureSize(64, 32);
      Mask_piece.mirror = true;
      setRotation(Mask_piece, 0F, 0F, 0F);
      Left_cheek = new ModelRenderer(this, 0, 16);
      Left_cheek.addBox(-1.7F, -1.3F, -1F, 4, 2, 2);
      Left_cheek.setRotationPoint(0F, 11F, 0F);
      Left_cheek.setTextureSize(64, 32);
      Left_cheek.mirror = true;
      setRotation(Left_cheek, 0F, 0F, 0F);
      Bottom_cheek = new ModelRenderer(this, 0, 16);
      Bottom_cheek.addBox(-2F, -0.5F, -1F, 4, 2, 2);
      Bottom_cheek.setRotationPoint(0F, 11F, 0F);
      Bottom_cheek.setTextureSize(64, 32);
      Bottom_cheek.mirror = true;
      setRotation(Bottom_cheek, 0F, 0F, 0F);
      Back_of_head = new ModelRenderer(this, 0, 16);
      Back_of_head.addBox(-2F, -1.3F, -0.8F, 4, 2, 2);
      Back_of_head.setRotationPoint(0F, 11F, 0F);
      Back_of_head.setTextureSize(64, 32);
      Back_of_head.mirror = true;
      setRotation(Back_of_head, 0F, 0F, 0F);
      Back_of_right_eye = new ModelRenderer(this, 13, 16);
      Back_of_right_eye.addBox(-1.7F, -3F, -0.8F, 1, 2, 2);
      Back_of_right_eye.setRotationPoint(0F, 11F, 0F);
      Back_of_right_eye.setTextureSize(64, 32);
      Back_of_right_eye.mirror = true;
      setRotation(Back_of_right_eye, 0F, 0F, 0F);
      Back_of_left_eye = new ModelRenderer(this, 13, 16);
      Back_of_left_eye.addBox(0.7F, -3F, -0.8F, 1, 2, 2);
      Back_of_left_eye.setRotationPoint(0F, 11F, 0F);
      Back_of_left_eye.setTextureSize(64, 32);
      Back_of_left_eye.mirror = true;
      setRotation(Back_of_left_eye, 0F, 0F, 0F);
      Lowerjaw_Right = new ModelRenderer(this, 24, 0);
      Lowerjaw_Right.addBox(-1F, -0.8F, -4.5F, 1, 1, 4);
      Lowerjaw_Right.setRotationPoint(0F, 12F, 0F);
      Lowerjaw_Right.setTextureSize(64, 32);
      Lowerjaw_Right.mirror = true;
      setRotation(Lowerjaw_Right, 0F, 0F, 0F);
      Upperjaw_Right = new ModelRenderer(this, 24, 6);
      Upperjaw_Right.addBox(-1.3F, -0.5F, -5F, 2, 1, 4);
      Upperjaw_Right.setRotationPoint(0F, 11F, 0F);
      Upperjaw_Right.setTextureSize(64, 32);
      Upperjaw_Right.mirror = true;
      setRotation(Upperjaw_Right, 0F, 0F, 0F);
      Upperjaw_Left = new ModelRenderer(this, 24, 6);
      Upperjaw_Left.addBox(-0.7F, -0.5F, -5F, 2, 1, 4);
      Upperjaw_Left.setRotationPoint(0F, 11F, 0F);
      Upperjaw_Left.setTextureSize(64, 32);
      Upperjaw_Left.mirror = true;
      setRotation(Upperjaw_Left, 0F, 0F, 0F);
      Upperjaw_Left.mirror = false;
      Lowerjaw_Left = new ModelRenderer(this, 24, 0);
      Lowerjaw_Left.addBox(0F, -0.8F, -4.5F, 1, 1, 4);
      Lowerjaw_Left.setRotationPoint(0F, 12F, 0F);
      Lowerjaw_Left.setTextureSize(64, 32);
      Lowerjaw_Left.mirror = true;
      setRotation(Lowerjaw_Left, 0F, 0F, 0F);
      Lowerjaw_Left.mirror = false;
      Muzzletip_Right = new ModelRenderer(this, 24, 12);
      Muzzletip_Right.addBox(-0.8F, -0.9F, -4.9F, 1, 1, 4);
      Muzzletip_Right.setRotationPoint(0F, 11F, 0F);
      Muzzletip_Right.setTextureSize(64, 32);
      Muzzletip_Right.mirror = true;
      setRotation(Muzzletip_Right, 0F, 0F, 0F);
      Muzzletip_Left = new ModelRenderer(this, 24, 12);
      Muzzletip_Left.addBox(-0.2F, -0.9F, -4.9F, 1, 1, 4);
      Muzzletip_Left.setRotationPoint(0F, 11F, 0F);
      Muzzletip_Left.setTextureSize(64, 32);
      Muzzletip_Left.mirror = true;
      setRotation(Muzzletip_Left, 0F, 0F, 0F);
      Muzzletip_Left.mirror = false;
      Segment1_Left = new ModelRenderer(this, 0, 21);
      Segment1_Left.addBox(0.2F, -0.7F, -4F, 1, 1, 3);
      Segment1_Left.setRotationPoint(0F, 11F, 0F);
      Segment1_Left.setTextureSize(64, 32);
      Segment1_Left.mirror = true;
      setRotation(Segment1_Left, 0F, 0F, 0F);
      Segment1_Left.mirror = false;
      Segment1_Right = new ModelRenderer(this, 0, 21);
      Segment1_Right.addBox(-1.2F, -0.7F, -4F, 1, 1, 3);
      Segment1_Right.setRotationPoint(0F, 11F, 0F);
      Segment1_Right.setTextureSize(64, 32);
      Segment1_Right.mirror = true;
      setRotation(Segment1_Right, 0F, 0F, 0F);
      Segment2_Left = new ModelRenderer(this, 36, 16);
      Segment2_Left.addBox(0F, -1F, -3F, 1, 1, 3);
      Segment2_Left.setRotationPoint(0F, 11F, 0F);
      Segment2_Left.setTextureSize(64, 32);
      Segment2_Left.mirror = true;
      setRotation(Segment2_Left, 0F, 0F, 0F);
      Segment2_Left.mirror = false;
      Segment2_Right = new ModelRenderer(this, 36, 16);
      Segment2_Right.addBox(-1F, -1F, -3F, 1, 1, 3);
      Segment2_Right.setRotationPoint(0F, 11F, 0F);
      Segment2_Right.setTextureSize(64, 32);
      Segment2_Right.mirror = true;
      setRotation(Segment2_Right, 0F, 0F, 0F);
      Middlemuzzle_Right = new ModelRenderer(this, 0, 21);
      Middlemuzzle_Right.addBox(-0.7F, -1.1F, -4F, 1, 1, 3);
      Middlemuzzle_Right.setRotationPoint(0F, 11F, 0F);
      Middlemuzzle_Right.setTextureSize(64, 32);
      Middlemuzzle_Right.mirror = true;
      setRotation(Middlemuzzle_Right, 0F, 0F, 0F);
      Middlemuzzle_Left = new ModelRenderer(this, 0, 21);
      Middlemuzzle_Left.addBox(-0.3F, -1.1F, -4F, 1, 1, 3);
      Middlemuzzle_Left.setRotationPoint(0F, 11F, 0F);
      Middlemuzzle_Left.setTextureSize(64, 32);
      Middlemuzzle_Left.mirror = true;
      setRotation(Middlemuzzle_Left, 0F, 0F, 0F);
      Middlemuzzle_Left.mirror = false;
      Topmuzzle_Right = new ModelRenderer(this, 32, 23);
      Topmuzzle_Right.addBox(-0.6F, -1.3F, -2.5F, 1, 1, 3);
      Topmuzzle_Right.setRotationPoint(0F, 11F, 0F);
      Topmuzzle_Right.setTextureSize(64, 32);
      Topmuzzle_Right.mirror = true;
      setRotation(Topmuzzle_Right, 0F, 0F, 0F);
      Topmuzzle_Left = new ModelRenderer(this, 32, 23);
      Topmuzzle_Left.addBox(-0.4F, -1.3F, -2.5F, 1, 1, 3);
      Topmuzzle_Left.setRotationPoint(0F, 11F, 0F);
      Topmuzzle_Left.setTextureSize(64, 32);
      Topmuzzle_Left.mirror = true;
      setRotation(Topmuzzle_Left, 0F, 0F, 0F);
      Topmuzzle_Left.mirror = false;
      Fronttooth_Left = new ModelRenderer(this, 27, 23);
      Fronttooth_Left.addBox(1.2F, -3.3F, -3.6F, 0, 1, 1);
      Fronttooth_Left.setRotationPoint(0F, 11F, 0F);
      Fronttooth_Left.setTextureSize(64, 32);
      Fronttooth_Left.mirror = true;
      setRotation(Fronttooth_Left, 0.8028515F, 0F, 0F);
      Fronttooth_Right = new ModelRenderer(this, 27, 23);
      Fronttooth_Right.addBox(-1.1F, -3.3F, -3.6F, 0, 1, 1);
      Fronttooth_Right.setRotationPoint(0F, 11F, 0F);
      Fronttooth_Right.setTextureSize(64, 32);
      Fronttooth_Right.mirror = true;
      setRotation(Fronttooth_Right, 0.8028515F, 0F, 0F);
      Left_Hip = new ModelRenderer(this, 9, 21);
      Left_Hip.addBox(0F, -1.5F, -1F, 1, 2, 2);
      Left_Hip.setRotationPoint(2F, 20.5F, 0F);
      Left_Hip.setTextureSize(64, 32);
      Left_Hip.mirror = true;
      setRotation(Left_Hip, 0F, 0F, 0F);
      Left_Hip.mirror = false;
      Left_Lower_leg = new ModelRenderer(this, 42, 7);
      Left_Lower_leg.addBox(0F, 0.4F, 1.1F, 1, 2, 1);
      Left_Lower_leg.setRotationPoint(2F, 20.5F, 0F);
      Left_Lower_leg.setTextureSize(64, 32);
      Left_Lower_leg.mirror = true;
      setRotation(Left_Lower_leg, -0.669215F, 0F, 0F);
      Left_Upper_leg = new ModelRenderer(this, 19, 13);
      Left_Upper_leg.addBox(0F, -0.2F, -1F, 1, 2, 1);
      Left_Upper_leg.setRotationPoint(2F, 20.5F, 0F);
      Left_Upper_leg.setTextureSize(64, 32);
      Left_Upper_leg.mirror = true;
      setRotation(Left_Upper_leg, 0.669215F, 0F, 0F);
      Left_Upper_leg.mirror = false;
      Left_Foot = new ModelRenderer(this, 0, 26);
      Left_Foot.addBox(0F, 2.4F, -1.4F, 1, 1, 2);
      Left_Foot.setRotationPoint(2F, 20.5F, 0F);
      Left_Foot.setTextureSize(64, 32);
      Left_Foot.mirror = true;
      setRotation(Left_Foot, 0F, 0F, 0F);
      Left_Foot.mirror = false;
      Le_Curve = new ModelRenderer(this, 0, 30);
      Le_Curve.addBox(0F, 0.5F, -0.1F, 1, 1, 1);
      Le_Curve.setRotationPoint(2F, 20.5F, 0F);
      Le_Curve.setTextureSize(64, 32);
      Le_Curve.mirror = true;
      setRotation(Le_Curve, 0F, 0F, 0F);
      Le_Curve.mirror = false;
      Left_Front_bump_1 = new ModelRenderer(this, 31, 28);
      Left_Front_bump_1.addBox(3.8F, -1.2F, -1.2F, 1, 1, 1);
      Left_Front_bump_1.setRotationPoint(-2F, 20.5F, 0F);
      Left_Front_bump_1.setTextureSize(64, 32);
      Left_Front_bump_1.mirror = true;
      setRotation(Left_Front_bump_1, 0F, 0F, 0F);
      Left_Front_bump_1.mirror = false;
      Left_Front_bump_2 = new ModelRenderer(this, 31, 28);
      Left_Front_bump_2.addBox(3.8F, -0.8F, -1.2F, 1, 1, 1);
      Left_Front_bump_2.setRotationPoint(-2F, 20.5F, 0F);
      Left_Front_bump_2.setTextureSize(64, 32);
      Left_Front_bump_2.mirror = true;
      setRotation(Left_Front_bump_2, 0F, 0F, 0F);
      Left_Front_bump_2.mirror = false;
      Left_Top_bump_1 = new ModelRenderer(this, 5, 30);
      Left_Top_bump_1.addBox(3.8F, -1.7F, -0.7F, 1, 1, 1);
      Left_Top_bump_1.setRotationPoint(-2F, 20.5F, 0F);
      Left_Top_bump_1.setTextureSize(64, 32);
      Left_Top_bump_1.mirror = true;
      setRotation(Left_Top_bump_1, 0F, 0F, 0F);
      Left_Top_bump_2 = new ModelRenderer(this, 5, 30);
      Left_Top_bump_2.addBox(3.8F, -1.7F, -0.3F, 1, 1, 1);
      Left_Top_bump_2.setRotationPoint(-2F, 20.5F, 0F);
      Left_Top_bump_2.setTextureSize(64, 32);
      Left_Top_bump_2.mirror = true;
      setRotation(Left_Top_bump_2, 0F, 0F, 0F);
      Left_Top_bump_2.mirror = false;
      Left_Back_bump_1 = new ModelRenderer(this, 5, 30);
      Left_Back_bump_1.addBox(3.8F, -1.2F, 0.2F, 1, 1, 1);
      Left_Back_bump_1.setRotationPoint(-2F, 20.5F, 0F);
      Left_Back_bump_1.setTextureSize(64, 32);
      Left_Back_bump_1.mirror = true;
      setRotation(Left_Back_bump_1, 0F, 0F, 0F);
      Left_Back_bump_2 = new ModelRenderer(this, 5, 30);
      Left_Back_bump_2.addBox(3.8F, -0.8F, 0.2F, 1, 1, 1);
      Left_Back_bump_2.setRotationPoint(-2F, 20.5F, 0F);
      Left_Back_bump_2.setTextureSize(64, 32);
      Left_Back_bump_2.mirror = true;
      setRotation(Left_Back_bump_2, 0F, 0F, 0F);
      Right_Hip = new ModelRenderer(this, 9, 21);
      Right_Hip.addBox(-1F, -1.5F, -1F, 1, 2, 2);
      Right_Hip.setRotationPoint(-2F, 20.5F, 0F);
      Right_Hip.setTextureSize(64, 32);
      Right_Hip.mirror = true;
      setRotation(Right_Hip, 0F, 0F, 0F);
      Right_Foot = new ModelRenderer(this, 0, 26);
      Right_Foot.addBox(-1F, 2.4F, -1.4F, 1, 1, 2);
      Right_Foot.setRotationPoint(-2F, 20.5F, 0F);
      Right_Foot.setTextureSize(64, 32);
      Right_Foot.mirror = true;
      setRotation(Right_Foot, 0F, 0F, 0F);
      Right_Curve = new ModelRenderer(this, 0, 30);
      Right_Curve.addBox(-1F, 0.5F, -0.1F, 1, 1, 1);
      Right_Curve.setRotationPoint(-2F, 20.5F, 0F);
      Right_Curve.setTextureSize(64, 32);
      Right_Curve.mirror = true;
      setRotation(Right_Curve, 0F, 0F, 0F);
      Right_Lower_leg = new ModelRenderer(this, 42, 7);
      Right_Lower_leg.addBox(-1F, 0.4F, 1.1F, 1, 2, 1);
      Right_Lower_leg.setRotationPoint(-2F, 20.5F, 0F);
      Right_Lower_leg.setTextureSize(64, 32);
      Right_Lower_leg.mirror = true;
      setRotation(Right_Lower_leg, -0.669215F, 0F, 0F);
      Right_Upper_leg = new ModelRenderer(this, 19, 13);
      Right_Upper_leg.addBox(-1F, -0.2F, -1F, 1, 2, 1);
      Right_Upper_leg.setRotationPoint(-2F, 20.5F, 0F);
      Right_Upper_leg.setTextureSize(64, 32);
      Right_Upper_leg.mirror = true;
      setRotation(Right_Upper_leg, 0.669215F, 0F, 0F);
      Right_Top_bump_1 = new ModelRenderer(this, 5, 30);
      Right_Top_bump_1.addBox(-0.8F, -1.7F, -0.7F, 1, 1, 1);
      Right_Top_bump_1.setRotationPoint(-2F, 20.5F, 0F);
      Right_Top_bump_1.setTextureSize(64, 32);
      Right_Top_bump_1.mirror = true;
      setRotation(Right_Top_bump_1, 0F, 0F, 0F);
      Right_Top_bump_2 = new ModelRenderer(this, 5, 30);
      Right_Top_bump_2.addBox(-0.8F, -1.7F, -0.3F, 1, 1, 1);
      Right_Top_bump_2.setRotationPoint(-2F, 20.5F, 0F);
      Right_Top_bump_2.setTextureSize(64, 32);
      Right_Top_bump_2.mirror = true;
      setRotation(Right_Top_bump_2, 0F, 0F, 0F);
      Right_Front_bump_1 = new ModelRenderer(this, 31, 28);
      Right_Front_bump_1.addBox(-0.8F, -1.2F, -1.2F, 1, 1, 1);
      Right_Front_bump_1.setRotationPoint(-2F, 20.5F, 0F);
      Right_Front_bump_1.setTextureSize(64, 32);
      Right_Front_bump_1.mirror = true;
      setRotation(Right_Front_bump_1, 0F, 0F, 0F);
      Right_Front_bump_2 = new ModelRenderer(this, 31, 28);
      Right_Front_bump_2.addBox(-0.8F, -0.8F, -1.2F, 1, 1, 1);
      Right_Front_bump_2.setRotationPoint(-2F, 20.5F, 0F);
      Right_Front_bump_2.setTextureSize(64, 32);
      Right_Front_bump_2.mirror = true;
      setRotation(Right_Front_bump_2, 0F, 0F, 0F);
      Right_Back_bump_1 = new ModelRenderer(this, 5, 30);
      Right_Back_bump_1.addBox(-0.8F, -1.2F, 0.2F, 1, 1, 1);
      Right_Back_bump_1.setRotationPoint(-2F, 20.5F, 0F);
      Right_Back_bump_1.setTextureSize(64, 32);
      Right_Back_bump_1.mirror = true;
      setRotation(Right_Back_bump_1, 0F, 0F, 0F);
      Right_Back_bump_2 = new ModelRenderer(this, 5, 30);
      Right_Back_bump_2.addBox(-0.8F, -0.8F, 0.2F, 1, 1, 1);
      Right_Back_bump_2.setRotationPoint(-2F, 20.5F, 0F);
      Right_Back_bump_2.setTextureSize(64, 32);
      Right_Back_bump_2.mirror = true;
      setRotation(Right_Back_bump_2, 0F, 0F, 0F);
      Right_Upperarm = new ModelRenderer(this, 0, 11);
      Right_Upperarm.addBox(-1F, -1F, -0.5F, 1, 3, 1);
      Right_Upperarm.setRotationPoint(-2F, 15F, 0F);
      Right_Upperarm.setTextureSize(64, 32);
      Right_Upperarm.mirror = true;
      setRotation(Right_Upperarm, 0.4014257F, 0F, 0F);
      Right_Lowerarm = new ModelRenderer(this, 26, 28);
      Right_Lowerarm.addBox(-1F, 0.3F, 1F, 1, 3, 1);
      Right_Lowerarm.setRotationPoint(-2F, 15F, 0F);
      Right_Lowerarm.setTextureSize(64, 32);
      Right_Lowerarm.mirror = true;
      setRotation(Right_Lowerarm, -0.779305F, 0F, 0F);
      Frontright_shoulder = new ModelRenderer(this, 40, 13);
      Frontright_shoulder.addBox(-1F, -1.2F, -0.6F, 1, 1, 1);
      Frontright_shoulder.setRotationPoint(-2F, 15F, 0F);
      Frontright_shoulder.setTextureSize(64, 32);
      Frontright_shoulder.mirror = true;
      setRotation(Frontright_shoulder, 0.4014257F, 0F, 0F);
      Backright_shoulder = new ModelRenderer(this, 40, 13);
      Backright_shoulder.addBox(-1F, -1.2F, -0.4F, 1, 1, 1);
      Backright_shoulder.setRotationPoint(-2F, 15F, 0F);
      Backright_shoulder.setTextureSize(64, 32);
      Backright_shoulder.mirror = true;
      setRotation(Backright_shoulder, 0.4014257F, 0F, 0F);
      Sideright_shoulder = new ModelRenderer(this, 40, 13);
      Sideright_shoulder.addBox(-1.1F, -1.1F, -0.5F, 1, 1, 1);
      Sideright_shoulder.setRotationPoint(-2F, 15F, 0F);
      Sideright_shoulder.setTextureSize(64, 32);
      Sideright_shoulder.mirror = true;
      setRotation(Sideright_shoulder, 0.4014257F, 0F, 0F);
      Left_Upperarm = new ModelRenderer(this, 0, 11);
      Left_Upperarm.addBox(0F, -1F, -0.5F, 1, 3, 1);
      Left_Upperarm.setRotationPoint(2F, 15F, 0F);
      Left_Upperarm.setTextureSize(64, 32);
      Left_Upperarm.mirror = true;
      setRotation(Left_Upperarm, 0.4014257F, 0F, 0F);
      Frontleft_shoulder = new ModelRenderer(this, 40, 13);
      Frontleft_shoulder.addBox(0F, -1.2F, -0.6F, 1, 1, 1);
      Frontleft_shoulder.setRotationPoint(2F, 15F, 0F);
      Frontleft_shoulder.setTextureSize(64, 32);
      Frontleft_shoulder.mirror = true;
      setRotation(Frontleft_shoulder, 0.4014257F, 0F, 0F);
      Left_Lowerarm = new ModelRenderer(this, 26, 28);
      Left_Lowerarm.addBox(0F, 0.3F, 1F, 1, 3, 1);
      Left_Lowerarm.setRotationPoint(2F, 15F, 0F);
      Left_Lowerarm.setTextureSize(64, 32);
      Left_Lowerarm.mirror = true;
      setRotation(Left_Lowerarm, -0.779305F, 0F, 0F);
      Backleft_shoulder = new ModelRenderer(this, 40, 13);
      Backleft_shoulder.addBox(0F, -1.2F, -0.4F, 1, 1, 1);
      Backleft_shoulder.setRotationPoint(2F, 15F, 0F);
      Backleft_shoulder.setTextureSize(64, 32);
      Backleft_shoulder.mirror = true;
      setRotation(Backleft_shoulder, 0.4014257F, 0F, 0F);
      Sideleft_shoulder = new ModelRenderer(this, 40, 13);
      Sideleft_shoulder.addBox(0.1F, -1.12F, -0.5F, 1, 1, 1);
      Sideleft_shoulder.setRotationPoint(2F, 15F, 0F);
      Sideleft_shoulder.setTextureSize(64, 32);
      Sideleft_shoulder.mirror = true;
      setRotation(Sideleft_shoulder, 0.4014257F, 0F, 0F);
      Tailcurve1_Left = new ModelRenderer(this, 7, 26);
      Tailcurve1_Left.addBox(-1.1F, -1F, 0F, 3, 2, 1);
      Tailcurve1_Left.setRotationPoint(0F, 19.1F, 1F);
      Tailcurve1_Left.setTextureSize(64, 32);
      Tailcurve1_Left.mirror = true;
      setRotation(Tailcurve1_Left, 0.4537856F, 0F, 0F);
      Tailcurve1_Right = new ModelRenderer(this, 7, 26);
      Tailcurve1_Right.addBox(-1.1F, -1F, 0F, 3, 2, 1);
      Tailcurve1_Right.setRotationPoint(-0.8F, 19.1F, 1F);
      Tailcurve1_Right.setTextureSize(64, 32);
      Tailcurve1_Right.mirror = true;
      setRotation(Tailcurve1_Right, 0.4537856F, 0F, 0F);
      Tailbase1_Left_Spine = new ModelRenderer(this, 31, 18);
      Tailbase1_Left_Spine.addBox(1.5F, -1.4F, -0.3F, 0, 2, 2);
      Tailbase1_Left_Spine.setRotationPoint(0F, 19.5F, 1.5F);
      Tailbase1_Left_Spine.setTextureSize(64, 32);
      Tailbase1_Left_Spine.mirror = true;
      setRotation(Tailbase1_Left_Spine, -0.0872665F, 0F, 0F);
      Tailbase1_Right_Spine = new ModelRenderer(this, 31, 18);
      Tailbase1_Right_Spine.addBox(-1.5F, -1.4F, -0.3F, 0, 2, 2);
      Tailbase1_Right_Spine.setRotationPoint(0F, 19.5F, 1.5F);
      Tailbase1_Right_Spine.setTextureSize(64, 32);
      Tailbase1_Right_Spine.mirror = true;
      setRotation(Tailbase1_Right_Spine, -0.0872665F, 0F, 0F);
      Segment1_Right_T = new ModelRenderer(this, 20, 18);
      Segment1_Right_T.addBox(-1.9F, -1F, 0F, 3, 2, 2);
      Segment1_Right_T.setRotationPoint(0F, 20F, 1F);
      Segment1_Right_T.setTextureSize(64, 32);
      Segment1_Right_T.mirror = true;
      setRotation(Segment1_Right_T, -0.4712389F, 0F, 0F);
      Segment1_Left_T = new ModelRenderer(this, 20, 18);
      Segment1_Left_T.addBox(-1.1F, -1F, 0F, 3, 2, 2);
      Segment1_Left_T.setRotationPoint(0F, 20F, 1F);
      Segment1_Left_T.setTextureSize(64, 32);
      Segment1_Left_T.mirror = true;
      setRotation(Segment1_Left_T, -0.4712389F, 0F, 0F);
      Segment2_RightBottom = new ModelRenderer(this, 16, 23);
      Segment2_RightBottom.addBox(-1.7F, -0.2F, 0F, 3, 1, 2);
      Segment2_RightBottom.setRotationPoint(0F, 20.8F, 2.6F);
      Segment2_RightBottom.setTextureSize(64, 32);
      Segment2_RightBottom.mirror = true;
      setRotation(Segment2_RightBottom, -0.2094395F, 0F, 0F);
      Segment2_LeftTop = new ModelRenderer(this, 16, 23);
      Segment2_LeftTop.addBox(-1.3F, -0.8F, 0F, 3, 1, 2);
      Segment2_LeftTop.setRotationPoint(0F, 20.8F, 2.6F);
      Segment2_LeftTop.setTextureSize(64, 32);
      Segment2_LeftTop.mirror = true;
      setRotation(Segment2_LeftTop, -0.2094395F, 0F, 0F);
      Segment2_LeftBottom = new ModelRenderer(this, 16, 23);
      Segment2_LeftBottom.addBox(-1.3F, -0.2F, 0F, 3, 1, 2);
      Segment2_LeftBottom.setRotationPoint(0F, 20.8F, 2.6F);
      Segment2_LeftBottom.setTextureSize(64, 32);
      Segment2_LeftBottom.mirror = true;
      setRotation(Segment2_LeftBottom, -0.2094395F, 0F, 0F);
      Segment2_RightTop = new ModelRenderer(this, 16, 23);
      Segment2_RightTop.addBox(-1.7F, -0.8F, 0F, 3, 1, 2);
      Segment2_RightTop.setRotationPoint(0F, 20.8F, 2.6F);
      Segment2_RightTop.setTextureSize(64, 32);
      Segment2_RightTop.mirror = true;
      setRotation(Segment2_RightTop, -0.2094395F, 0F, 0F);
      Segment3_RightTop = new ModelRenderer(this, 15, 29);
      Segment3_RightTop.addBox(-1.5F, -0.7F, -0.2F, 3, 1, 2);
      Segment3_RightTop.setRotationPoint(0F, 21.2F, 4.5F);
      Segment3_RightTop.setTextureSize(64, 32);
      Segment3_RightTop.mirror = true;
      setRotation(Segment3_RightTop, -0.0523599F, 0F, 0F);
      Segment3_RightBottom = new ModelRenderer(this, 15, 29);
      Segment3_RightBottom.addBox(-1.5F, -0.4F, -0.2F, 3, 1, 2);
      Segment3_RightBottom.setRotationPoint(0F, 21.2F, 4.5F);
      Segment3_RightBottom.setTextureSize(64, 32);
      Segment3_RightBottom.mirror = true;
      setRotation(Segment3_RightBottom, -0.0523599F, 0F, 0F);
      Tailbase3_Left_Spine = new ModelRenderer(this, 11, 30);
      Tailbase3_Left_Spine.addBox(1.2F, -0.3F, 0.7F, 0, 1, 1);
      Tailbase3_Left_Spine.setRotationPoint(0F, 21.2F, 4.5F);
      Tailbase3_Left_Spine.setTextureSize(64, 32);
      Tailbase3_Left_Spine.mirror = true;
      setRotation(Tailbase3_Left_Spine, 0.6981317F, 0F, 0F);
      Tailbase3_Right_Spine = new ModelRenderer(this, 11, 30);
      Tailbase3_Right_Spine.addBox(-1.2F, -0.3F, 0.7F, 0, 1, 1);
      Tailbase3_Right_Spine.setRotationPoint(0F, 21.2F, 4.5F);
      Tailbase3_Right_Spine.setTextureSize(64, 32);
      Tailbase3_Right_Spine.mirror = true;
      setRotation(Tailbase3_Right_Spine, 0.6981317F, 0F, 0F);
      Segment4_Right = new ModelRenderer(this, 35, 0);
      Segment4_Right.addBox(-1.3F, -0.6F, -0.7F, 2, 1, 2);
      Segment4_Right.setRotationPoint(0F, 21.3F, 6.5F);
      Segment4_Right.setTextureSize(64, 32);
      Segment4_Right.mirror = true;
      setRotation(Segment4_Right, 0.1396263F, 0F, 0F);
      Segment4_Left = new ModelRenderer(this, 35, 0);
      Segment4_Left.addBox(-0.7F, -0.6F, -0.7F, 2, 1, 2);
      Segment4_Left.setRotationPoint(0F, 21.3F, 6.5F);
      Segment4_Left.setTextureSize(64, 32);
      Segment4_Left.mirror = true;
      setRotation(Segment4_Left, 0.1396263F, 0F, 0F);
      Segment5_Right = new ModelRenderer(this, 36, 4);
      Segment5_Right.addBox(-1.1F, -0.6F, 0F, 2, 1, 1);
      Segment5_Right.setRotationPoint(0F, 21.1F, 7.7F);
      Segment5_Right.setTextureSize(64, 32);
      Segment5_Right.mirror = true;
      setRotation(Segment5_Right, 0.0523599F, 0F, 0F);
      Segment5_Left = new ModelRenderer(this, 36, 4);
      Segment5_Left.addBox(-0.9F, -0.6F, 0F, 2, 1, 1);
      Segment5_Left.setRotationPoint(0F, 21.1F, 7.7F);
      Segment5_Left.setTextureSize(64, 32);
      Segment5_Left.mirror = true;
      setRotation(Segment5_Left, 0.0523599F, 0F, 0F);
      Tailbase5_Right_Spine = new ModelRenderer(this, 11, 30);
      Tailbase5_Right_Spine.addBox(-0.9F, -0.3F, 0.3F, 0, 1, 1);
      Tailbase5_Right_Spine.setRotationPoint(0F, 21.2F, 7.5F);
      Tailbase5_Right_Spine.setTextureSize(64, 32);
      Tailbase5_Right_Spine.mirror = true;
      setRotation(Tailbase5_Right_Spine, 0.8028515F, 0F, 0F);
      Tailbase5_Left_Spine = new ModelRenderer(this, 11, 30);
      Tailbase5_Left_Spine.addBox(0.9F, -0.3F, 0.3F, 0, 1, 1);
      Tailbase5_Left_Spine.setRotationPoint(0F, 21.2F, 7.5F);
      Tailbase5_Left_Spine.setTextureSize(64, 32);
      Tailbase5_Left_Spine.mirror = true;
      setRotation(Tailbase5_Left_Spine, 0.8028515F, 0F, 0F);
      Segment6_Right = new ModelRenderer(this, 37, 7);
      Segment6_Right.addBox(-0.9F, -0.6F, 0F, 1, 1, 1);
      Segment6_Right.setRotationPoint(0F, 21.1F, 8.7F);
      Segment6_Right.setTextureSize(64, 32);
      Segment6_Right.mirror = true;
      setRotation(Segment6_Right, -0.0698132F, 0F, 0F);
      Segment6_Left = new ModelRenderer(this, 37, 7);
      Segment6_Left.addBox(-0.1F, -0.6F, 0F, 1, 1, 1);
      Segment6_Left.setRotationPoint(0F, 21.1F, 8.7F);
      Segment6_Left.setTextureSize(64, 32);
      Segment6_Left.mirror = true;
      setRotation(Segment6_Left, -0.0698132F, 0F, 0F);
      Segment7_Right = new ModelRenderer(this, 37, 10);
      Segment7_Right.addBox(-0.7F, -0.5F, 0F, 1, 1, 1);
      Segment7_Right.setRotationPoint(0F, 21.1F, 9.7F);
      Segment7_Right.setTextureSize(64, 32);
      Segment7_Right.mirror = true;
      setRotation(Segment7_Right, -0.1745329F, 0F, 0F);
      Segment7_Left = new ModelRenderer(this, 37, 10);
      Segment7_Left.addBox(-0.3F, -0.5F, 0F, 1, 1, 1);
      Segment7_Left.setRotationPoint(0F, 21.1F, 9.7F);
      Segment7_Left.setTextureSize(64, 32);
      Segment7_Left.mirror = true;
      setRotation(Segment7_Left, -0.1745329F, 0F, 0F);
      Tailbase7_Left_Spine = new ModelRenderer(this, 11, 30);
      Tailbase7_Left_Spine.addBox(0.5F, -0.3F, 0.3F, 0, 1, 1);
      Tailbase7_Left_Spine.setRotationPoint(0F, 21.2F, 9.5F);
      Tailbase7_Left_Spine.setTextureSize(64, 32);
      Tailbase7_Left_Spine.mirror = true;
      setRotation(Tailbase7_Left_Spine, 0.5410521F, 0F, 0F);
      Tailbase7_Right_Spine = new ModelRenderer(this, 11, 30);
      Tailbase7_Right_Spine.addBox(-0.5F, -0.3F, 0.3F, 0, 1, 1);
      Tailbase7_Right_Spine.setRotationPoint(0F, 21.2F, 9.5F);
      Tailbase7_Right_Spine.setTextureSize(64, 32);
      Tailbase7_Right_Spine.mirror = true;
      setRotation(Tailbase7_Right_Spine, 0.5410521F, 0F, 0F);
      Segment8_Right = new ModelRenderer(this, 35, 13);
      Segment8_Right.addBox(-0.5F, -0.3F, 0F, 1, 1, 1);
      Segment8_Right.setRotationPoint(0F, 21.1F, 10.7F);
      Segment8_Right.setTextureSize(64, 32);
      Segment8_Right.mirror = true;
      setRotation(Segment8_Right, -0.3141593F, 0F, 0F);
      Main = new ModelRenderer(this, 0, 0);
      Main.addBox(-2F, 0F, -1.5F, 4, 7, 3);
      Main.setRotationPoint(0F, 14F, 0F);
      Main.setTextureSize(64, 32);
      Main.mirror = true;
      setRotation(Main, 0F, 0F, 0F);
      Neck = new ModelRenderer(this, 15, 8);
      Neck.addBox(-1F, -1.9F, -1F, 2, 2, 2);
      Neck.setRotationPoint(0F, 14F, 0F);
      Neck.setTextureSize(64, 32);
      Neck.mirror = true;
      setRotation(Neck, 0F, 0F, 0F);
      Belly = new ModelRenderer(this, 15, 0);
      Belly.addBox(-1.5F, 0.5F, -1.8F, 3, 6, 1);
      Belly.setRotationPoint(0F, 14F, 0F);
      Belly.setTextureSize(64, 32);
      Belly.mirror = true;
      setRotation(Belly, 0F, 0F, 0F);
      Back_Right_Spine = new ModelRenderer(this, 31, 18);
      Back_Right_Spine.addBox(-1.5F, -2.1F, 0.1F, 0, 2, 2);
      Back_Right_Spine.setRotationPoint(0F, 16F, 0F);
      Back_Right_Spine.setTextureSize(64, 32);
      Back_Right_Spine.mirror = true;
      setRotation(Back_Right_Spine, -0.7853982F, 0F, 0F);
      Back_Left_Spine = new ModelRenderer(this, 31, 18);
      Back_Left_Spine.addBox(1.5F, -2.1F, 0.1F, 0, 2, 2);
      Back_Left_Spine.setRotationPoint(0F, 16F, 0F);
      Back_Left_Spine.setTextureSize(64, 32);
      Back_Left_Spine.mirror = true;
      setRotation(Back_Left_Spine, -0.7853982F, 0F, 0F);
      Neck_Left_Spine = new ModelRenderer(this, 11, 30);
      Neck_Left_Spine.addBox(0.8F, -1.7F, -0.3F, 0, 1, 1);
      Neck_Left_Spine.setRotationPoint(0F, 14F, 0F);
      Neck_Left_Spine.setTextureSize(64, 32);
      Neck_Left_Spine.mirror = true;
      setRotation(Neck_Left_Spine, -0.7853982F, 0F, 0F);
      Neck_Right_Spine = new ModelRenderer(this, 11, 30);
      Neck_Right_Spine.addBox(-0.8F, -1.7F, -0.3F, 0, 1, 1);
      Neck_Right_Spine.setRotationPoint(0F, 14F, 0F);
      Neck_Right_Spine.setTextureSize(64, 32);
      Neck_Right_Spine.mirror = true;
      setRotation(Neck_Right_Spine, -0.7853982F, 0F, 0F);
    Left_Arm = new ModelRenderer(this, "Left_Arm");
    Left_Arm.setRotationPoint(0F, 0F, 0F);
    setRotation(Left_Arm, 0F, 0F, 0F);
    Left_Arm.mirror = true;
    Right_Arm = new ModelRenderer(this, "Right_Arm");
    Right_Arm.setRotationPoint(0F, 0F, 0F);
    setRotation(Right_Arm, 0F, 0F, 0F);
    Right_Arm.mirror = true;
    Head = new ModelRenderer(this, "Head");
    Head.setRotationPoint(0F, 0F, 0F);
    setRotation(Head, 0F, 0F, 0F);
    Head.mirror = true;
    Left_Leg = new ModelRenderer(this, "Left_Leg");
    Left_Leg.setRotationPoint(0F, 0F, 0F);
    setRotation(Left_Leg, 0F, 0F, 0F);
    Left_Leg.mirror = true;
    Tail = new ModelRenderer(this, "Tail");
    Tail.setRotationPoint(0F, 0F, 0F);
    setRotation(Tail, 0F, 0F, 0F);
    Tail.mirror = true;
    Right_Leg = new ModelRenderer(this, "Right_Leg");
    Right_Leg.setRotationPoint(0F, 0F, 0F);
    setRotation(Right_Leg, 0F, 0F, 0F);
    Right_Leg.mirror = true;
    Body = new ModelRenderer(this, "Body");
    Body.setRotationPoint(0F, 17.5F, 0F);
    setRotation(Body, 0F, 0F, 0F);
    Body.mirror = true;
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Right_cheek.render(f5);
    Right_eye.render(f5);
    Left_eye.render(f5);
    Mask_piece.render(f5);
    Left_cheek.render(f5);
    Bottom_cheek.render(f5);
    Back_of_head.render(f5);
    Back_of_right_eye.render(f5);
    Back_of_left_eye.render(f5);
    Lowerjaw_Right.render(f5);
    Upperjaw_Right.render(f5);
    Upperjaw_Left.render(f5);
    Lowerjaw_Left.render(f5);
    Muzzletip_Right.render(f5);
    Muzzletip_Left.render(f5);
    Segment1_Left.render(f5);
    Segment1_Right.render(f5);
    Segment2_Left.render(f5);
    Segment2_Right.render(f5);
    Middlemuzzle_Right.render(f5);
    Middlemuzzle_Left.render(f5);
    Topmuzzle_Right.render(f5);
    Topmuzzle_Left.render(f5);
    Fronttooth_Left.render(f5);
    Fronttooth_Right.render(f5);
    Left_Hip.render(f5);
    Left_Lower_leg.render(f5);
    Left_Upper_leg.render(f5);
    Left_Foot.render(f5);
    Le_Curve.render(f5);
    Left_Front_bump_1.render(f5);
    Left_Front_bump_2.render(f5);
    Left_Top_bump_1.render(f5);
    Left_Top_bump_2.render(f5);
    Left_Back_bump_1.render(f5);
    Left_Back_bump_2.render(f5);
    Right_Hip.render(f5);
    Right_Foot.render(f5);
    Right_Curve.render(f5);
    Right_Lower_leg.render(f5);
    Right_Upper_leg.render(f5);
    Right_Top_bump_1.render(f5);
    Right_Top_bump_2.render(f5);
    Right_Front_bump_1.render(f5);
    Right_Front_bump_2.render(f5);
    Right_Back_bump_1.render(f5);
    Right_Back_bump_2.render(f5);
    Right_Upperarm.render(f5);
    Right_Lowerarm.render(f5);
    Frontright_shoulder.render(f5);
    Backright_shoulder.render(f5);
    Sideright_shoulder.render(f5);
    Left_Upperarm.render(f5);
    Frontleft_shoulder.render(f5);
    Left_Lowerarm.render(f5);
    Backleft_shoulder.render(f5);
    Sideleft_shoulder.render(f5);
    Tailcurve1_Left.render(f5);
    Tailcurve1_Right.render(f5);
    Tailbase1_Left_Spine.render(f5);
    Tailbase1_Right_Spine.render(f5);
    Segment1_Right_T.render(f5);
    Segment1_Left_T.render(f5);
    Segment2_RightBottom.render(f5);
    Segment2_LeftTop.render(f5);
    Segment2_LeftBottom.render(f5);
    Segment2_RightTop.render(f5);
    Segment3_RightTop.render(f5);
    Segment3_RightBottom.render(f5);
    Tailbase3_Left_Spine.render(f5);
    Tailbase3_Right_Spine.render(f5);
    Segment4_Right.render(f5);
    Segment4_Left.render(f5);
    Segment5_Right.render(f5);
    Segment5_Left.render(f5);
    Tailbase5_Right_Spine.render(f5);
    Tailbase5_Left_Spine.render(f5);
    Segment6_Right.render(f5);
    Segment6_Left.render(f5);
    Segment7_Right.render(f5);
    Segment7_Left.render(f5);
    Tailbase7_Left_Spine.render(f5);
    Tailbase7_Right_Spine.render(f5);
    Segment8_Right.render(f5);
    Main.render(f5);
    Neck.render(f5);
    Belly.render(f5);
    Back_Right_Spine.render(f5);
    Back_Left_Spine.render(f5);
    Neck_Left_Spine.render(f5);
    Neck_Right_Spine.render(f5);
    Left_Arm.render(f5);
    Right_Arm.render(f5);
    Head.render(f5);
    Left_Leg.render(f5);
    Tail.render(f5);
    Right_Leg.render(f5);
    Body.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
