// Date: 5/8/2012 4:12:29 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package pixelmon.Pokemon;

import net.minecraft.src.*;

public class ModelOddish extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer leftleg;
    ModelRenderer rightleg;
    ModelRenderer rightfoot;
    ModelRenderer leftfoot;
    ModelRenderer lefteye;
    ModelRenderer righteye;
    ModelRenderer leaf1;
    ModelRenderer leaf2;
    ModelRenderer leaf3;
    ModelRenderer leaf4;
  
  public ModelOddish()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(-1.5F, -2F, -1.5F, 3, 3, 3);
      Body.setRotationPoint(0F, 21.5F, 0F);
      Body.setTextureSize(32, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 6, 6);
      leftleg.addBox(-0.5F, 0F, -0.5F, 1, 1, 1);
      leftleg.setRotationPoint(0.9F, 22F, 0.3F);
      leftleg.setTextureSize(32, 32);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 6, 8);
      rightleg.addBox(-0.5F, 0F, -0.5F, 1, 1, 1);
      rightleg.setRotationPoint(-0.9F, 22F, 0.3F);
      rightleg.setTextureSize(32, 32);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      rightfoot = new ModelRenderer(this, 0, 9);
      rightfoot.addBox(-0.5F, 0F, -1.5F, 1, 1, 2);
      rightfoot.setRotationPoint(-0.9F, 22.8F, 0.3F);
      rightfoot.setTextureSize(32, 32);
      rightfoot.mirror = true;
      setRotation(rightfoot, 0.1047198F, 0F, 0F);
      leftfoot = new ModelRenderer(this, 0, 6);
      leftfoot.addBox(-0.5F, 0F, -1.5F, 1, 1, 2);
      leftfoot.setRotationPoint(0.9F, 22.8F, 0.3F);
      leftfoot.setTextureSize(32, 32);
      leftfoot.mirror = true;
      setRotation(leftfoot, 0.1047198F, 0F, 0F);
      lefteye = new ModelRenderer(this, 0, 13);
      lefteye.addBox(-0.5F, -0.5F, -2F, 1, 1, 1);
      lefteye.setRotationPoint(0F, 21.5F, 0F);
      lefteye.setTextureSize(32, 32);
      setRotation(lefteye, -0.7853982F, -0.6283185F, 0F);
      lefteye.mirror = false;
      righteye = new ModelRenderer(this, 0, 13);
      righteye.addBox(-0.5F, -0.5F, -2F, 1, 1, 1);
      righteye.setRotationPoint(0F, 21.5F, 0F);
      righteye.setTextureSize(32, 32);
      righteye.mirror = true;
      setRotation(righteye, -0.7853982F, 0.6283185F, 0F);
      leaf1 = new ModelRenderer(this, 13, -3);
      leaf1.addBox(0F, -6.5F, -1.5F, 1, 5, 3);
      leaf1.setRotationPoint(0F, 21.5F, 0F);
      leaf1.setTextureSize(32, 32);
      leaf1.mirror = true;
      setRotation(leaf1, 0F, 0F, 0.4886922F);
      leaf2 = new ModelRenderer(this, 13, 6);
      leaf2.addBox(-1.5F, -6.5F, 0F, 3, 5, 1);
      leaf2.setRotationPoint(0F, 21.5F, 0F);
      leaf2.setTextureSize(32, 32);
      leaf2.mirror = true;
      setRotation(leaf2, -0.4886922F, 0F, 0F);
      leaf3 = new ModelRenderer(this, 13, 13);
      leaf3.addBox(-1.5F, -6.5F, -1F, 3, 5, 1);
      leaf3.setRotationPoint(0F, 21.5F, 0F);
      leaf3.setTextureSize(32, 32);
      leaf3.mirror = true;
      setRotation(leaf3, 0.4886922F, 0F, 0F);
      leaf4 = new ModelRenderer(this, 13, 20);
      leaf4.addBox(-1F, -6.5F, -1.5F, 1, 5, 3);
      leaf4.setRotationPoint(0F, 21.5F, 0F);
      leaf4.setTextureSize(32, 32);
      leaf4.mirror = true;
      setRotation(leaf4, 0F, 0F, -0.4886922F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
    leftleg.render(f5);
    rightleg.render(f5);
    rightfoot.render(f5);
    leftfoot.render(f5);
    lefteye.render(f5);
    righteye.render(f5);
    leaf1.render(f5);
    leaf2.render(f5);
    leaf3.render(f5);
    leaf4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
