// Date: 17/06/2012 9:16:41 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package pixelmon.Trainers;

import net.minecraft.src.*;

public class ModelYoungster02 extends ModelBase {
	// fields
	ModelRenderer armwithpokeball;
	ModelRenderer body;
	ModelRenderer leftarm;
	ModelRenderer rightleg;
	ModelRenderer leftleg;
	ModelRenderer head;
	ModelRenderer dot_on_pokeball;
	ModelRenderer Pokeball;
	ModelRenderer rightarm;

	public ModelYoungster02() {
		textureWidth = 64;
	    textureHeight = 32;
	    
	      body = new ModelRenderer(this, 16, 16);
	      body.addBox(-4F, 0F, -2F, 7, 9, 3);
	      body.setRotationPoint(0F, 5F, 0F);
	      body.setTextureSize(64, 32);
	      body.mirror = true;
	      setRotation(body, 0F, 0F, 0F);
	      leftarm = new ModelRenderer(this, 48, 16);
	      leftarm.addBox(0F, -2F, -1F, 2, 10, 2);
	      leftarm.setRotationPoint(3F, 7F, -1F);
	      leftarm.setTextureSize(64, 32);
	      leftarm.mirror = true;
	      setRotation(leftarm, 0F, 0F, -0.0394506F);
	      head = new ModelRenderer(this, 0, 0);
	      head.addBox(-2.5F, -5F, -3F, 5, 5, 5);
	      head.setRotationPoint(0F, 5F, 0F);
	      head.setTextureSize(64, 32);
	      head.mirror = true;
	      setRotation(head, 0F, 0F, 0F);
	      rightleg = new ModelRenderer(this, 0, 16);
	      rightleg.addBox(-2F, 0F, -2F, 3, 10, 3);
	      rightleg.setRotationPoint(-2F, 14F, 0F);
	      rightleg.setTextureSize(64, 32);
	      rightleg.mirror = true;
	      setRotation(rightleg, 0F, 0F, 0F);
	      dot_on_pokeball = new ModelRenderer(this, 26, 0);
	      dot_on_pokeball.addBox(-1.5F, 8.5F, -3.1F, 1, 1, 1);
	      dot_on_pokeball.setRotationPoint(0F, 0F, 0F);
	      dot_on_pokeball.setTextureSize(64, 32);
	      dot_on_pokeball.mirror = true;
	      setRotation(dot_on_pokeball, 0.0523599F, 0F, 0F);
	      Pokeball = new ModelRenderer(this, 22, 0);
	      Pokeball.addBox(-2F, 8F, -3F, 2, 2, 2);
	      Pokeball.setRotationPoint(-4F, 6F, 0.5F);
	      Pokeball.setTextureSize(64, 32);
	      Pokeball.mirror = true;
	      setRotation(Pokeball, 0.0523599F, 0F, 0F);
	      rightarm = new ModelRenderer(this, 40, 16);
	      rightarm.addBox(-1.7F, -1.8F, -1F, 2, 10, 2);
	      rightarm.setRotationPoint(-4F, 7F, -1F);
	      rightarm.setTextureSize(64, 32);
	      rightarm.mirror = true;
	      setRotation(rightarm, 0F, 0F, 0.0394444F);
	      leftleg = new ModelRenderer(this, 0, 16);
	      leftleg.addBox(-2F, 0F, -2F, 3, 10, 3);
	      leftleg.setRotationPoint(2F, 14F, 0F);
	      leftleg.setTextureSize(64, 32);
	      leftleg.mirror = true;
	      setRotation(leftleg, 0F, 0F, 0F);
	  }
	
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5);
		body.render(f5);
		leftarm.render(f5);
		rightleg.render(f5);
		leftleg.render(f5);
		head.render(f5);
		dot_on_pokeball.render(f5);
		Pokeball.render(f5);
		rightarm.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}
